---

- name: Make backups directory
  ansible.builtin.file:
    path: "{{ backup_dest }}"
    state: directory

- name: Create fstab entry
  ansible.builtin.mount:
    path: "{{ backup_dest }}"
    src: LABEL=backups
    fstype: xfs
    state: mounted

- name: Label node for backups
  ansible.builtin.command:
    cmd: "kubectl label node {{ inventory_hostname }} {{ lan_domain }}/local-backups=true"
  delegate_to: "{{ k8s_controller }}"