---
service:
  type: LoadBalancer
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6
  additionalServices:
    ssh:
      enabled: true
      type: LoadBalancer
      ipFamilyPolicy: PreferDualStack
      ipFamilies:
        - IPv4
        - IPv6

ports:
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
  websecure:
    enabled: true
    port: 8443
    exposedPort: 443
    expose:
      default: true
      ssh: true
    protocol: TCP
  traefik:
    port: 9000
    expose:
      default: false
  ssh:
    port: 2222
    expose:
      ssh: true
    exposedPort: 22
    protocol: TCP

entryPoints:
  ssh:
    address: ":22"

ingressClass:
  enabled: true
  isDefaultClass: false


additionalIngressClasses:
  - enabled: true
    name: traefik-ssh
    isDefaultClass: false
    annotations:
      ingressclass.kubernetes.io/is-default-class: "false"
      traefik.ingress.kubernetes.io/service: traefik-ssh

dashboard:
  enabled: true

logs:
  general:
    level: INFO
  access:
    enabled: true
pod:
  securityContext:
    capabilities:
      add:
      - NET_BIND_SERVICE

tlsStore:
  default:
    defaultCertificate:
      secretName: wildcard.milco.casa