---
service:
  type: LoadBalancer
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6

ports:
  web:
    redirections:
      entryPoint:
        to: websecure
        scheme: https
        permanent: true
  websecure:
    enabled: true
    port: 8443
    exposedPort: 443
    protocol: TCP
  traefik:
    port: 9000
    expose:
      default: false

ingressClass:
  enabled: true
  isDefaultClass: false

dashboard:
  enabled: true

logs:
  general:
    level: INFO
  access:
    enabled: true
pod:
  securityContext:
    capabilities:
      add:
      - NET_BIND_SERVICE

tlsStore:
  default:
    defaultCertificate:
      secretName: wildcard.milco.casa