---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-oidc-config
  namespace: harbor
spec:
  encryptedData:
    harbor-config.json: AgAnrJMFs0hU2ra+1gUfc2EYPPr1bQU29C/COtyZtZJzv9NUDw3bG7P89PubR4Y7bkEK2q/6AkEmbwTq4TrxRsOopzkuPwmYI4YuLouJWBMMTkszm8eG4KSyD5m2IHLxV+vOoNY1cELyp4QQDc+KHEkmERf7BCHn0XQxwgyR6ME47/+/E9O9mItZDZh5PK3DGankSskBWfuUWozPaovdvfcCUi/UZDRIjC0P75B1/rvx0lTIBJg7EWB9l96/ug0xV6WsE2Ztd6FZ5/hkVM/Im2YUccTjPNpGTNIsYC6cIL45zMj7BwqA4txR3Ffh9RplZeSZsFZmvQeJihPHcydhoVkPywMZKnRaCbB4zPu9JGOy6oNvgjigIGveTNlSllMy5iFqrU/oHV7LvA2vk6Qor5+cuHJbI0qW3HHyQ4+VTFCMsKVpITGH1D9v8/i4Yg1k58u/bqsXfH6BqoO6l6ASZ0C7hXBD5yznyVlrG3Tf24OKuKvs6tmJntzOo8YzaaSxvmfnnpEYbToXy7HHg3FrVysOxImCLYyCyfA9u+HCKfemoL/7XQqHoA96/+XTsXlUDLrJnDTYJuYoJYLfnLQgTP1Rhoe7fZuc+2Mh3PRA0VEmZBM73oGG11zWRG6IziT6uymGqn2IzZ10FpGNdylg2JR8GDIMmFKvHlozLeiBN7o+sI9+KXZsXpW4jOkitENf++E0xswNN2/SAD2f18zFiWUtBPNTjPpPO2UB1FAHSgquV7FnNeg5z1GI2vDiPF2p/eIzZ87t9xwDGRBukj/wulQ7v/5HTUPWonD8eO1YfGcJORq8n+VGnLpRPavLqPxPmWWcd2r+LXJwdIofSJBremFQSoK0KOI4eWqnoEu9H4yYZyhO12LMmKB34Qmw0163ozW0NZHSzCryYRB6DIilpf0DxGHV1L9gZYfhXDXtETrZBaE+OHphMu7TWiqstx8Iip0zty6oqq4wkkSgq1gwqfLs9AOFiv7k6XxORQYfv6lioK8ImrcAPaPW5goH+7Wqa8p6DlYK2GdLGDck43daydfKcAcmoQsJAyyl8irPXHcKzNUetu3WrL/x7m+R1clly32rONlIt3E2BFw/Ak5MnBdB8+1ZWjoIeNeYGy9SiOYCyioh6b754NLAFc+v115638JIgmA8UPfqVhsYwM4Pq+kYpf1qvdCDMwVB5/s=
  template:
    metadata:
      creationTimestamp: null
      name: harbor-oidc-config
      namespace: harbor
