---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-oidc-config
  namespace: harbor
spec:
  encryptedData:
    harbor-config.json: AgBEhMAOietrFONjc98I5yYXe79kbOsPfbDOLBneRAur0OXjpN+K0zo9jmV8sqf8i+i2NyaFl3FjZmMvms6FoHTkN3rXS7NcNbHkvJbbBlXVtZu/0/HnerLf7xNmf9Eo3uPZbKfsoCnwTnhpLPekaZWgPKGGQOZYv+RO+/12JIKR/b5he/VahWlwC/sTV8bS+2orn41LGrOT1SODAxz/kimnUEBpKn++7aNpfkAB0XNUA8XzZddzgZuD+NKwYTjVLxFn8qsMiteFWI2svCQEHbFFGeo+yR9NZE9zQyMUeSPcIIdqiBebC6oyBZfRpDrMfKDb7Oos2Q3zPiOTg1PUc1M9x8TN46WNBBxTq+AnYR1Fw+4IfHDKC7YmEe0zHjlCmqCzeVRtinbh8sp8mprP9h/HTi0EaRo/SHr1THks8c/Lzqvsm+AMbgCf67qEmDrjwMFITPVlcW7mnM3KuuMSEvb09BsmrlL0ZEWhX7kAb1q1D/pyhAMKw9NZzyBJ4xvJWGWhn6zV/+OZogPPmJl1+u+4ltTfLFJBs54PTDTnZzGneHk3605xf1FGhB++GS8d+IC1qnnGb/3F5GuYWuMMRsKt5jfCiphmfTBR3gUsBI6GpononuP2f+agPj34XQy0Ghr+i1CZz8FNpofA2+CLz/NVOAV8DgYr6mQOC7TxAQH7w3shPt/x+vayaaj0ry1Z0K7mOeyoXi33FFvuhC32Z2R3dXu4l22tr05H/czimoxBR6KYxD2YU91rYY4IySZCBpQmW5LWk3RBE2VkZ/UVM5qRDZYLyUovVYQ46LUIuuUi0ZUEbm0V6ZJzlKRoooPuLZRHyStzwrqFXn/oVWNp8I2g0mPtk4VAzEI5RApjOqcoSGqE2acK+xL4fPwZx9Rtso+kcTUZVglPj/BDibeWRKObuNzVQVHpf3W23F+fFYIfSohtXPu3VuI9+JGrr/xDKuXWxSU9htZhjjTNGfXVVG2jN8dOfRFeDDofxjAnQCDR0W05hWQmPi3Eq8Hu824OzNyb3fpXKgbAiKO76F1nJkJCm3HaYO8mrmL5CMbAS3tXPkkjHd2pqaCiYw==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-oidc-config
      namespace: harbor
