---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-oidc-config
  namespace: harbor
spec:
  encryptedData:
    harbor-config.json: AgAMN0S1wXztK57w1+EyM/oo3W346vEYVnUHW2wrsg5n6Rg/DDVQyGpep1/bvo0Npx55zZtZTpvemz42fX+4fnPoeXCqtJZZRolZoKu9TTpWjLdxbWga62LMrRvMJxcFQYtBtjgAWmq72GqaPhwa+aDL5Hl9wj1HNPMa/Jfjvot710hzAGIMb903NISA2GHCQ0kvGxjYhAPZxRPdgsZ0V/wRmcegiNlqfS9PX7ab7aGNqETPc6MAvgWhg2G5lhIWa87XivFRAb8FJ0ku+tEfCvf6ATCZFtPotCI6FCBrMM2HMt8NuziFfXBITb6iC3qrp/HfOFR8PtAbRfPltqzvGsQr6aXD9cksoEM3CegESwtwqKRpX7dzaCwX6rzmijHV+tdor3mAH+azgLfT7BvucNz7q7nkT+4a8qtgcJobmz+G/dT8VrSXIJw9UicCYXyx+fP8CRJ8RWzG+/epCYehP6a7ocMOzIySky27U41OsYceUX8BBVXV19Y9rbrt/wlNT0xkmxhi1rsk2AX1TRDj/LWEracrzV3lo85gQHQNo+olbk1uF8XXc1t/zQzyrbwOFEGM6pMB6NFTabP47Uj12Wh+7FV/k7g6JIhWp3fRCvRAcI1wLqCTa+xg50qJNvG/jthx5EpjEyVx1wqzuHT1eYHNfQ56Kh73OzsBRQH179mtus+yTgiLGL4YYLiXMw6YdCNcTaY6uv05deEwkrRDSSccwO7JOKz1dnhWp6d3wcdE7hezBxzFYiGdp/TijcZsf89F0VrI3pYUVk/Gj7W0QB9jAr4g943O3Iddq5y+ZbI0iiWGItHQi7fwBhcQbOYEpEOv53E5eW2kOBd38xdMe/eSmpy6G5hS/NzATWMpTUqXWoyq6wMOKPG3t1nY6751gL2HhC7EUjaLz+O9hixG27qumPPEVcXWmU3Ekc3dnOA4b2vd9KIkKfIcHRWKMcRZhwn0VWzp/xa5dHZTlp0QKrl2Vi/JRQWYGiYFZTmYLKb6MS02VZxe1l01l75hJL5/1AHE7rITGR/+WQHwFFGgF4xy7WThQGkBeATb6v5sPrgxARCIQfyQZkSOCphDBU/b
  template:
    metadata:
      creationTimestamp: null
      name: harbor-oidc-config
      namespace: harbor
