---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-secrets
  namespace: harbor
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: AgCEbDrg40qASn5ImEvyyEPcBFU5h/uiwyuxn00dbZB/Fki79WQ2AQlwhJm0eDjVcB8JLTKDRrqykoUVINYs2udwymU8NAORRVy69umZonOcRGAW8t5LuDXufdDU4bquc3QajaU3aoSTVepqgZZEyPr+TW5i6b5P9rBe6JkJIUF9odwNe8E7mAdujZNCN3TyqzJ48Bi+/UuWDbkGEIZdLSx2JnbCGO0YYTe5aW1h6Jhub8esjq+MUNWMuq6jkrceHPIWawJJ/aJwqxUy5gNkWN/19QgI3q6K34LAlzkLwEmP+jUI7hcX+Co0yJuDO7M/UYRbZdShh2+Cy4h1lyaRzlKc1/KRckxoJSAUEieddrbHRn8lNxur9s9w8zrf0L+Cdw0DHyXOkSBQtF/0xeTssedrNfV7PUwBqUtyre9LvErFv7TTMYggFvQ4SSXf7spG89I3A2Fh74V/mRzgeOsjZ2G1s/kj1uHo5xwaUeVj/j0ks/IGWrsbiW4kuK1ub6AS3Z5Pz9+zhoNGFok8TJQwBKOTIEwq2SQm3kCK8WRvdMWbkWYb1RnbRBvPukDwMX/37Lgck+YTpFYWkTXtr2HqbRoYz2mhD+VgdfgQvO884B/YtW7etvFG+C0NBliJXIWbHTpYed2ivateL9OBap8yy0erOFoS4epFxCJwuf6qEbyM922s+mf+ZVvPBlR6yJyPuPBdiIlpm8q5rGmmaHAdJlPdsjySJpioVJF3o71Z4Agr2k50AKLjPVh3mzcZQ06ixqcv3w==
    secretKey: AgBrPhwODcDXIwc0OEyA3ZXhd6itkBPjpcjJkm7P7wNlj18yYrms9ne+g962aNp5MMo14P8jSgSUvqj/hpUq/jG0+FI0TRDvlbR9vuGorUOm+gKGLcjeraH561PTv0e0c5Hku9RD+UkLezmA82SVdRMLAmXGUSRNf65n1lfBcprBLrLZf5dfkEvbkZgrZst1DNypHGMeW9goi9jw2nfE2A0n3AQ1dPcBRujlyoiVm+EwVtZLPxdvVKxquolPhjJoZ546ZYeZE/2OfGfmvhVqH0/bJjg+s3DZv+v4EVM3CJzlsLYEKpqeoFM/VZXG9mc+TAnG0eb9vXKGKXXFAGj3V64ePGfnfPkkOcNah4pfjg197/BswAO50nY6aYTG9EFJU7eiIUpAyGop8o9teP17CiGRNHBp7Y1E0DlHVGEu230eA9yS2Arkou5mmy5X9ESeCY6JckQohYDcr6sds8Gt4fUArMESVdwunMsojcHEI99oVxsKZXqGa76F113hGh0w7laPfJL7EApO1csOp6UjCZf8ZYqjC1QyCaAnJc+5vGc33g73yURN/tuvWsZ/hqeiC2PzZFt3DwbO1PoGW3W2uuAP9DklVO/COgt3MwPAk4N50h5hCADaHxfgDcOkTJU9LoctyK+dK4PY8QvKbd79D0NrIQjf2rhA9w6S+JKGcH6PkNV9leg+MogeSQdE8VI7b35pCwmuLVoR+AIv+Vcklu7K
  template:
    metadata:
      creationTimestamp: null
      name: harbor-secrets
      namespace: harbor
