---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: harbor-secrets
  namespace: harbor
spec:
  encryptedData:
    HARBOR_ADMIN_PASSWORD: AgBwoEkdVE+z8y1UxQgTrUnL8ytz8Ioc4sc3Gaa2NTPc5ZdWD5oR3sdJfl29k5B1IHK7SGqiZQfdXQ9JlSOBbFdFhAn0R1YA9fCJ7N0ae5nLWslHweJlrbgdm/SYczv8h9w2zPCbuMX6bAgD/6NH1keJqn74lWOkgzFwSFuN8AJIh6CWGl7gxQqSvaEZYbZ3EVr4gTjuCF7M9ZVxUnVo5Wswfd2K0EIiS1Y4eMtlQ4FtbPhmihsQ3u3CBJdccKcHQUMQZngvJtCxGnEGJurKO91loxNPBwKxVmdlXlgRCJz7B4ZD5MdafiZtGK+e4LxDb2KPHJ7jFc1PrOOe/CLVAgHRwqzLZTfrVbTBO2qBVn+Q2a77nn/pFGAyoV+nYTnDLsBl+3r4t9ZB+c4jKQc5LcYewkNeKUQ/IDQk6uLRKcs6COWqdvsrcDCQ0aqMEjftYMU8FgO7z1lX9yH5OKCQP1m711diKOsy8+nTxRYHao0kg3CNtby6+LptkinqQQzY0MAOE5qLFgURIJheRJYoJ/6IT9hOhw7lA0Lt5QCj+FSoAcXkDvEPU8Yy08wokajFXYe5SmfWoZMblSwA2r+wu2Jeux6oal9T/9jQ5jH2k1hHaT/47CFBt+C3RyuVODexqlUx/nNtLJ0OZFR4VSkIYZccO+730hkFk1Byk//vQP+cXj+2svMrsyv7LqqwAW1jjkKzgouNlBqlSk4RiZ0pPyLY4A02hChfcBLyqJS4TVQF1w7KlpD/Dryq7N+gTa80EpKdFg==
    secretKey: AgCq5Lg0Um+4TjxIrrnKNaE20ndBx3818YXeKT9BHlDIcjmG1My8JaD1JJW7eufVs6YvZbWeBPUhnG79fJJSfU9RTrJUkhn4R5dFGCGy8Qoaqyhr/sb7QnbPbaYsv/UbbLxxrqJl0Ux6PGg2iBqX2ak3I9aWEsDPV7kSqIfrCHYHEHhKEIohWx+TBuapQfVG6k9GSL5aDW+PKi3gMlfsozONY/8Pemg5P6o37vGMWoxd/JqpFBpdcmJ6xTQGgvS+FLpqVPXezwYTwXFKAC4qRdLXU5+a8sQj1kqzlahD8LOCPCyKW00nPDeFQrnsiUjuS6vp8y6vRs5WSw4iNsLvOXn4RZSSRzy6npjQJ5jkyTipN5VWL9wlKBe50ZlJ3R+0hhvzwlmJUMUYK2deAnKp5Cewa4GmintBeST8ZBjL3ALrooXjFC8y7A08CkQfcvlcLNkNZQyHP/u67Yq4zK79IOqDgMSa5fPnlNv4tOr2sZrOwMyeVf34+MGp/bAnNxKa/ECvNmnpFj6Uy0FgRZ5u3iLWj5z0gylWuuANoxM3VsnRJiFsIIpxQXyNIZXwp7CcUXesFVa2ZLy78spfHeK/0whvbfDvVAdVFQLOJCpidE6tj7ggVC0eRQmJG+VJH9/JtKXs67RNife+n3zuj3eHFA0FbJjvMRB2RNmXDV33n6tuxIgP76EoJ6roTmyPklaAbHmxWlGL+9zvH4wVLagdeCqKbIchvK8vVtK9/hIQ1AeDjz2Um1Ovo4023bGKlzK4zjm0uw==
  template:
    metadata:
      creationTimestamp: null
      name: harbor-secrets
      namespace: harbor
