---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: velero-minio-secrets
  namespace: velero
spec:
  encryptedData:
    cloud: AgBI0Y65E6RVAFz6StesyV0iZC2xKnUBxJJAARq2QRa2lKPKzPrCHoPyhkAIxq1JvyAvCEE26y55eSdZ/SUdxeQSsFH1Q8WxjrGhhuXUOidgRDTJFEndT+hFqPhP2V7R75jSM9xnSI86UzltvWbmz6flR0KNg/8WcPTBYQ2sfn42VKDh9rnLYPyhZR0SJsDL2zWlC/lAeQ/gfqlA94ofUeSP4renE2udVh0FbWnK5+ZScrxFKtkn4nJDgwPgT4DWkQZlu8kcYDvcA3vFnpaXGL/cfu05ALtKFZeurVYDvldOpYQqOyFxNvAdJSlPCqiUkx1oYyUg+eDXv88l8edtqg56BBQ1SKL5F6GSNS17ipiSzAnbExBpLT4KvOCGNOpCPUXn/tyEMA5mw1q1Z90PTHTs/pSAXtK6F0rELt9iqZaInckGrL+8VmdvnEgkTqTazp/WrjoEQnRRCTMnmT/kuFkIV15/AUlNUU5kSgX70LU+o5hOeS0Jnj7sDKbgm8BF0dChiyLRUhTw+I3wK1xukytVe07Nmsjw0c65hMtUpWo/+6fiP4i1OoBsHIovMQ8zUWjSErsDiG9QhRUiTccAs/+h8lMS9mlN6HHdzJIR+7MwPTUGhclVj8+sHj1WTALBZo5YT1TlOFTucTmI3A1rYAbfbgTcyrW5kTrGqCbypLnHhXdDuwOn3cquyeU1OStgSqeyN+48GZCtEOxwF3y+JwF+aTVnLtdtvzg9U0PoY58oASxS8ScsN6TcfYpd0cTOzF0X397GvOcoCt0loI5tqCs+orPMY1icFO+J7XuwHKDSDQIHzA84DxZzcpwqCkvLlpM7LU9B8NoftZ6/3fH0Te7mBbxMxtKKWg==
  template:
    metadata:
      creationTimestamp: null
      name: velero-minio-secrets
      namespace: velero
