---
credentials:
  useSecret: true
  existingSecret: velero-minio-secrets

configuration:
  backupStorageLocation:
    - name: local
      provider: aws
      bucket: velero-backups
      default: true
      config:
        region: minio
        s3ForcePathStyle: "true"
        s3Url: https://minio-local.clt.milco.casa
    - name: backblaze
      provider: aws
      bucket: milco-cluster-backups
      prefix: velero
      config:
        region: us-west-002
        s3ForcePathStyle: true
        s3Url: https://s3.us-west-002.backblazeb2.com
      credential:
        name: velero-backblaze-secrets
        key: cloud

  # Explicitly disable VolumeSnapshotLocation if not needed
  volumeSnapshotLocation: []

defaultVolumesToFsBackup: true
deployNodeAgent: true
uploaderType: kopia

featureFlags:
  - EnableUnifiedRepo

initContainers:
  - name: velero-plugin-for-aws
    image: velero/velero-plugin-for-aws:v1.11.1
    volumeMounts:
      - mountPath: /target
        name: plugins

schedules:
  local-backups:
    schedule: "0 0 * * *"
    template:
      ttl: 720h  # 30 days (720 hours)
      includedNamespaces:
        - "*"
      excludedNamespaces:
        - minio
        - velero
      includedResources:
        - "*"
      excludedResources:
        - persistentvolumeclaims.plex.pms-config-plex-plex-media-server-0
      defaultVolumesToFsBackup: true
      includeClusterResources: true
      storageLocation: local
  off-site-backups:
    schedule: "0 3 * * *"
    template:
      ttl: 360h  # 15 days (360 hours)
      includedNamespaces:
        - "*"
      excludedNamespaces:
        - minio
        - velero
      includedResources:
        - "*"
      excludedResources:
        - persistentvolumeclaims.plex.pms-config-plex-plex-media-server-0
      defaultVolumesToFsBackup: true
      includeClusterResources: true
      storageLocation: backblaze