---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns-secrets
  namespace: external-dns
spec:
  encryptedData:
    openwrt-ssh-key: AgC6onUt6iSj176S8SDbhHIdrEZ7oWhbayaUyP1neQKJPoiNSfltBj38bxbNjVCF6DNYSeyGwpksWAPIqZikfJ/KUr6po2dVSsLhGkbwVW3KzKGAt7eT3W6mw/K19Uclg6av76lEw23qZV7WqWW9rvVo71mRGJ7KQKApAKiq6i9W84EiXJ6z4cdQQj53TntDdrQ/OUm9BNtdFHZbc1YjCaiHQCZAO9CIsIwydtx/NByFiK9gn77ZGsyApNCw1uHfG2qVUWBkGpVqi4Ng+2WCPE83vFgHuHcElWghORl7To4vrJEGxaOXkO7S0P3TXtWUDwidHsoeK0L0s8IO3hv3Jvol9iOlFN6hS1Yjb2HpiR1u2sIVuMGwkTEqr9T1QAs9pZlev5Gp472qQnYsvsQAGuUZIdDJflEozYR9E5z15mIPX/wfOMqFlhWhsyKI8gy4S9Msb7NmjiKVCjXRF7Ke6PnWqV5s6/dPBPCb6PhzhJPYeHCuNVq3EzNBciSiJ3rLbxv3Xb+q/IYfSgA47Ewtv1Yr0CvcAqh1qZaQOO0f5tQAdESpNUQBeWFZR0uVhPem5vBXl6p8eFl6p7BcLTLQWvnocOy3XSxj7fWVVCul0CQ5gNzHkJyKt2r6QoHtz4Kt4HvLT6n/y4IVghOVV4vzcBLA4rqvxXVBf/P6Mryyx4yQy+C+U6R72ctc7CCd8iRXnqLpVJGoZb09s4i41NqDZqLv1gOM9vk0Pnb8cjoyTrrXRqyRylwdxLPPPA5GMNaZhmoL6j65v74tg5k4rKjJPfgRoPuNP6z7YsaUmNofEkq7jez11vql45TuCiMxZbFvZbbrFXI3A0WqhUktj+EcVNMG0naoiirHQOenQCFYTkAhniqeZYKQdcoAUdmZh/ERJgYlicn5jV1drirqIgPsHusgUnxUI5cplMAqSiczYruPQUz/9ZORxGclTcfoKjJ40BqJDlGb6VoNOUMcHEAS0IBmikkRmChbHicJf6BmV0rQxNNcEfyyVg3CUiT9sPVrUaK4nNc9xanfarXMgJJ7aI4USdb7xzsLr786PBH4FfRDoJ6QJDzGvaHSUyBq4f5iakMiOz9JAOKi0PZh9cD3sjwLUngMImT51mDgZU40GDdTZ5/smv5LT8fa718pQZMXwAD6c2kVFYKHyxpV93sIbMG8UDGHBvMo7gx4UQ92gryNt+hleGFIgwgH9XYCdqByYvU1t4581R7gWfWJddBNe7xmXda9PLdb2z6dFQA=
  template:
    metadata:
      creationTimestamp: null
      name: external-dns-secrets
      namespace: external-dns
