---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns-secrets
  namespace: external-dns
spec:
  encryptedData:
    openwrt-password: AgCSrdFYfJharxpD/nOt6WjMsRJ6LZLqE7R78srlbl6xuS3uMn8aqJKDlxMfV+oWYSuPKYZXNA2jJX9WRDtNHLqWtQMdZ9wEsIv2m2xzUzmIlChYW6MjOMTAOSyDxLWNH6nG6+T/NXoUPQFncqMBj0HOS/WNgTfgD48AU/XyaBfsuwIEm+pVKYHufz9l0fL/S1k/mEtESE7sQleJ+v0tDaQe+i6Eaiuej3ckGgdAXJnLfQPwZ/3fbgZuIP9wlcqO60T5JrXMjUzqO+S9RhW6t0MgmbhPHPJ8rK6teQ1+Qp7FvWfnmOkp7Ar+dkX6G2gWI8c66CFQNiDgH4sn9zFZ/1tm37vpj3wKfKTOtj64yAZVPGR8xc+Kdf3ojjMdcfzxeXu9IJT2EcTfcdzPiB4D8p3NAln5U6jo66pisZKHQF/8v4FhMEEnl84h4l1Qt5uwkmmzGIp+TrRwqnQIqo8+EJfVw4CTcRVxd3mQ1+B/PEnFj2KWCwk7ZoAVSybuJSlueCzrwqI1DS5oy23soZfJ2VXfKC6aZrMlv8kinMPh+qf8WeJfH59k8Q5EHTqsQom4BxLG24R2G1YwEaL+yo3Rd7Reke4Jv6AyJsgo69RmYK/7LjYhxckKHxIdTBF5NrJGl7JZr1VOYduev0+dR/LsPtlKIHBcCCljwpFIhw0wMrhJdXBmbw+MKUAjH6K03tBJq+46lk+455e5ygLg6pIvWFyV1eQmDgcCkjuOmmmzJ9GqdmL3+I3cNu+mjWWiYfVHPX9toQ==
  template:
    metadata:
      creationTimestamp: null
      name: external-dns-secrets
      namespace: external-dns
