---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns-secrets
  namespace: external-dns
spec:
  encryptedData:
    openwrt-password: AgBZZscUDJhh8eZccZfIZcGVoaqJavXf/u1WdHQ+B1CPSBtJpiMP52gdi13L4CITKjrSlCFS032yaO24W1cdtuQfJjPMa2FSaHGtC0ganSMwCRzv4PB9DJ1wkQ6kgUzBqgqjvPrGDjCKO2ohnJCF+5Amc6DdUEXs42PpczNExAYlJdsXTrssn02ZngyyCArF1GDqZHNbJFEku0Zze8Yae4eAoK32mzSjKUkLZmiiI9NXezvL5Bb0nyHGx1qNMvOH75wNwuhFc5jEZFtU28jaNhbNsoHG+C8f7fzyQsTVMRpcBceMNauGYoxkO3cPen5RxA2oteOBtxKpATY5HOQeXjBmb4gLNy/F4k1G7IAygyEXzqvwlVpnDD9lQU14gu2YX9RTBpJPrN6GEOaGdq1IcfIYg5O2cGo/C3nTH/L6wUtFT2VIHrcuVXnuosl92zKIuaBDj4STG8N4Fo6Pysb7mEwMCOL46iPfVVEocBCKgQwlXSoHu1P58iHd46ZfBTcNkOooNE9Cc4MsybH19s5gBsGqshnrYdQOXU+8Nhgy4jpQvSlBkRvp2C/6Lh4t7wQvLMD+FrIUcj0n3xJUvddm3hi1UxVfvW53/R/TsZaFrTE2g3EBRr4ZY0VgQ43kZyXxY71Ey4j9jKXKKL753SFMwr7IwURoOTTERcZj/RkpEBy8flnkwe1MOgRpP5eukUBnDWEbijTx41basZw8NQEteT8CrISXnMcgT2deANEn3TOTBQ8ykWy6RZolq62fKXyrqCLY9A==
  template:
    metadata:
      creationTimestamp: null
      name: external-dns-secrets
      namespace: external-dns
