---

ipa_replicas: 1
ipa_directory_password: "{{ vault_ipa_directory_password }}"
ipa_admin_password: "{{ vault_ipa_admin_password }}"
ipa_admin_user: "admin"

ipa_new_user_password: "{{ vault_ipa_new_user_password }}"

ipa_dns_zones:
  - "{{ lan_tld }}."
  - "{{ lan_domain }}."
  - "{{ ceph_srv_zone }}"

ipa_srv_records:
  - name: _ceph-mon
    data:
      - 10 20 6789 mon1.{{ lan_domain }}.
      - 10 30 6789 mon2.{{ lan_domain }}.
      - 20 50 6789 mon3.{{ lan_domain }}.

ipa_dns_entries:
  - name: ipa-01
    type: A
    data: "{{ network_services['ipa-01'].ipv4 }}"
    zone: "{{ lan_domain }}"
  - name: ipa-01
    type: AAAA
    data: "{{ network_services['ipa-01'].ipv6 }}"
    zone: "{{ lan_domain }}"
  - name: ipa-02
    type: A
    data: "{{ network_services['ipa-02'].ipv4 }}"
    zone: "{{ lan_domain }}"
  - name: ipa-02
    type: AAAA
    data: "{{ network_services['ipa-02'].ipv6 }}"
    zone: "{{ lan_domain }}"
  - name: traefik
    type: A
    data: "{{ network_services['traefik'].ipv4 }}"
    zone: "{{ lan_domain }}"
  - name: traefik
    type: AAAA
    data: "{{ network_services['traefik'].ipv6 }}"
    zone: "{{ lan_domain }}"
  - name: argocd
    type: CNAME
    data: "traefik.{{ lan_domain }}."
    zone: "{{ lan_domain }}"
  - name: ceph
    type: CNAME
    data: "traefik.{{ lan_domain }}."
    zone: "{{ lan_domain }}"
  - name: minio
    type: CNAME
    data: "traefik.{{ lan_domain }}."
    zone: "{{ lan_domain }}"
  - name: minio-local
    type: CNAME
    data: "traefik.{{ lan_domain }}."
    zone: "{{ lan_domain }}"
  - name: nextcloud
    type: CNAME
    data: "traefik.{{ lan_domain }}."
    zone: "{{ lan_domain }}"
  - name: plex
    type: CNAME
    data: "traefik.{{ lan_domain }}."
    zone: "{{ lan_domain }}"
  - name: s3
    type: CNAME
    data: "traefik.{{ lan_domain }}."
    zone: "{{ lan_domain }}"
  - name: git
    type: CNAME
    data: "traefik.{{ lan_domain }}."
    zone: "{{ lan_domain }}"
  - name: plex-svc
    type: A
    data: "{{ network_services['plex-svc'].ipv4 }}"
    zone: "{{ lan_domain }}"
  - name: plex-svc
    type: AAAA
    data: "{{ network_services['plex-svc'].ipv6 }}"
    zone: "{{ lan_domain }}"

ipa_groups:
  - name: app-gitea-admins
  - name: app-gitea-users

ipa_users:
  - name: bmilco
    first_name: Brian
    last_name: Milco
    loginshell: /usr/bin/zsh
    groups:
      - name: admins
      - name: app-gitea-admins
    emails:
      - "{{ site_admin_email }}"
    ssh_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPQGjMgHnJcTrRNNSFLFbiBFIf4LeG1R4rxq7mBuhWGk {{ site_admin_email }}

...
