---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: backups-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1.75Ti
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  volumeMode: Filesystem
  hostPath:
    path: /mnt/backups
    type: Directory
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: clt.milco.casa/local-backups
          operator: In
          values:
          - "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-backups
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1.75Ti
  storageClassName: manual