mode: standalone

image:
  tag: RELEASE.2025-04-08T15-41-24Z

# Persistence configuration using the mounted drive
persistence:
  enabled: true
  existingClaim: "local-backups"

existingSecret: "minio-credentials"
buckets:
  - name: velero-backups
    policy: none
    purge: false

tolerations:
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: clt.milco.casa/local-backups
          operator: In
          values:
          - "true"

ingress:
  enabled: true
  ingressClassName: "traefik"
  path: /
  hosts:
    - minio-local.clt.milco.casa
  tls:
    - secretName: wildcard.milco.casa
      hosts:
        - minio-local.clt.milco.casa

consoleIngress:
  enabled: true
  ingressClassName: "traefik"
  path: /
  hosts:
    - minio.clt.milco.casa
  tls:
    - secretName: wildcard.milco.casa
      hosts:
        - minio.clt.milco.casa

oidc:
  enabled: true
  configUrl: "https://sso.clt.milco.casa/realms/homelab/.well-known/openid-configuration"
  existingClientSecretName: "minio-oidc-client"
  existingClientIdKey: "oidc.clientId"
  existingClientSecretKey: "oidc.clientSecret"
  claimName: "policy"
  scopes: "openid,profile,email"
  redirectUri: "https://minio.clt.milco.casa/oauth_callback"
  displayName: "Homelab"