---
- name: Get Keycloak passwords
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: keycloak-passwords
    namespace: keycloak
  register: keycloak_secrets

- name: Get Keycloak admin password
  ansible.builtin.set_fact:
    keycloak_admin_password: "{{ keycloak_secrets.resources[0].data['adminPassword'] | b64decode }}"
    svc_ldap_password: "{{ keycloak_secrets.resources[0].data['BIND_PASSWORD'] | b64decode }}"

- name: Create a new realm in Keycloak
  community.general.keycloak_realm:
    auth_keycloak_url: "{{ keycloak.url }}"
    auth_username: "{{ keycloak.admin_username }}"
    auth_password: "{{ keycloak_admin_password }}"
    auth_realm: "{{ keycloak.admin_realm }}"
    realm: "{{ keycloak.realm }}"
    sso_session_idle_timeout: 86400
    sso_session_max_lifespan: 172800
    sso_session_idle_timeout_remember_me: 86400
    sso_session_max_lifespan_remember_me: 172800
    state: present
    enabled: true
  register: realm_result

- name: Create LDAP user federation for LLDAP in Keycloak
  delegate_to: localhost
  community.general.keycloak_user_federation:
    auth_keycloak_url: "{{ keycloak.url }}"
    auth_username: "{{ keycloak.admin_username }}"
    auth_password: "{{ keycloak_admin_password }}"
    auth_realm: "{{ keycloak.admin_realm }}"
    realm: "{{ keycloak.realm }}"
    state: present
    name: "lldap"
    provider_id: "ldap"
    config:
      connectionUrl: "{{ lldap_url }}"
      usersDn: "{{ ldap_users_dn }}"
      bindDn: "{{ ldap_svc_dn }}"
      bindCredential: "{{ svc_ldap_password }}"
      vendor: "other"
      authType: "simple"
      usernameLDAPAttribute: "uid"
      rdnLDAPAttribute: "uid"
      uuidLDAPAttribute: "entryUUID"
      userObjectClasses: "inetOrgPerson, person"
      searchScope: 2
      editMode: "READ_ONLY"
      fullSyncPeriod: 86400  # 24hr sync
      changedSyncPeriod: -1  # lldap does not support timestamp filters
      syncRegistrations: false
      trustEmail: true
      pagination: true
    mappers:
      - name: "creation date"
        providerId: "user-attribute-ldap-mapper"
        config:
          user.model.attribute: "createTimestamp"
          ldap.attribute: "createTimestamp"
          read.only: "true"
          alwaysReadValueFromLDAP: "true"
          isMandatory: "false"
          is.binary.attribute: "false"
      - name: "email"
        providerId: "user-attribute-ldap-mapper"
        config:
          user.model.attribute: "email"
          ldap.attribute: "mail"
          read.only: "true"
          alwaysReadValueFromLDAP: "false"
          isMandatory: "false"
          is.binary.attribute: "false"
      - name: "first name"
        providerId: "user-attribute-ldap-mapper"
        config:
          user.model.attribute: "firstName"
          ldap.attribute: "givenName"
          read.only: "true"
          alwaysReadValueFromLDAP: "true"
          isMandatory: "true"
          is.binary.attribute: "false"
      - name: "last name"
        providerId: "user-attribute-ldap-mapper"
        config:
          user.model.attribute: "lastName"
          ldap.attribute: "sn"
          read.only: "true"
          alwaysReadValueFromLDAP: "true"
          isMandatory: "true"
          is.binary.attribute: "false"
      - name: "modify date"
        providerId: "user-attribute-ldap-mapper"
        config:
          user.model.attribute: "modifyTimestamp"
          ldap.attribute: "modifyTimestamp"
          read.only: "true"
          alwaysReadValueFromLDAP: "true"
          isMandatory: "false"
          is.binary.attribute: "false"
      - name: "username"
        providerId: "user-attribute-ldap-mapper"
        config:
          user.model.attribute: "username"
          ldap.attribute: "uid"
          read.only: "true"
          alwaysReadValueFromLDAP: "false"
          isMandatory: "true"
          is.binary.attribute: "false"
      - name: "groups"
        providerId: "group-ldap-mapper"
        config:
          groups.dn: "{{ ldap_groups_dn }}"
          group.name.ldap.attribute: "cn"
          group.object.classes: "groupOfUniqueNames"
          membership.ldap.attribute: "uniqueMember"
          membership.attribute.type: "DN"
          groups.path: ""
          mode: "LDAP_ONLY"
          user.roles.retrieve.strategy: "LOAD_GROUPS_BY_MEMBER_ATTRIBUTE"
          drop.non.existing.groups.during.sync: "false"
          preserve.group.inheritance: "true"
          alwaysReadValueFromLDAP: "true"

- name: Create openid client scope
  community.general.keycloak_clientscope:
    auth_keycloak_url: "{{ keycloak.url }}"
    auth_username: "{{ keycloak.admin_username }}"
    auth_password: "{{ keycloak_admin_password }}"
    auth_realm: "{{ keycloak.admin_realm }}"
    realm: "{{ keycloak.realm }}"
    state: present
    name: "openid"
    description: "Client scope for OpenID Connect standard claims"
    protocol: "openid-connect"
    attributes:
      include.in.token.scope: "true"
      display.on.consent.screen: "true"
      consent.screen.text: "Access to OpenID Connect claims"
      include.in.assigned.scope: "default"
    protocol_mappers:
      - name: "openid"
        protocol: "openid-connect"
        protocolMapper: "oidc-usermodel-property-mapper"
        config:
          user.model.attribute: "user.id"
          claim.name: "openid"
          jsonType.label: "String"
          id.token.claim: true
          access.token.claim: true
          userinfo.token.claim: true

- name: Create username client scope
  community.general.keycloak_clientscope:
    auth_keycloak_url: "{{ keycloak.url }}"
    auth_username: "{{ keycloak.admin_username }}"
    auth_password: "{{ keycloak_admin_password }}"
    auth_realm: "{{ keycloak.admin_realm }}"
    realm: "{{ keycloak.realm }}"
    state: present
    name: "username"
    description: "Client scope for including username in tokens"
    protocol: "openid-connect"
    attributes:
      include.in.token.scope: "true"
      display.on.consent.screen: "true"
      consent.screen.text: "Access to username"
      include.in.assigned.scope: "default"
    protocol_mappers:
      - name: "username"
        protocol: "openid-connect"
        protocolMapper: "oidc-usermodel-property-mapper"
        config:
          user.model.attribute: "username"
          claim.name: "username"
          jsonType.label: "String"
          id.token.claim: true
          access.token.claim: true
          userinfo.token.claim: true

- name: Create groups client scope
  community.general.keycloak_clientscope:
    auth_keycloak_url: "{{ keycloak.url }}"
    auth_username: "{{ keycloak.admin_username }}"
    auth_password: "{{ keycloak_admin_password }}"
    auth_realm: "{{ keycloak.admin_realm }}"
    realm: "{{ keycloak.realm }}"
    state: present
    name: "groups"
    description: "Client scope for including group memberships in tokens"
    protocol: "openid-connect"
    attributes:
      include.in.token.scope: "true"
      display.on.consent.screen: "true"
      consent.screen.text: "Access to group memberships"
      include.in.assigned.scope: "default"
    protocol_mappers:
      - name: "groups"
        protocol: "openid-connect"
        protocolMapper: "oidc-group-membership-mapper"
        config:
          claim.name: "groups"
          full.path: "false"
          id.token.claim: true
          access.token.claim: true
          userinfo.token.claim: true
