---

- name: Setup OpenWrt router
  hosts: router
  gather_facts: false
  remote_user: root
  tags:
    - never
    - openwrt
  roles:
    - role: openwrt

- name: Configure base OS
  hosts: metal
  tags:
    - config-os
    - configure-os
    - controllers
    - workers
  roles:
    - role: configure-os

- name: configure node
  hosts:
    - controllers
    - workers
  tags:
    - cluster
  vars:
    has_nvidia_card: false
  roles:
    - role: kube-vip
      tags:
        - vip
      when:
        - inventory_hostname in groups['controllers']
    - role: containerd
      when: k8s_runtime == 'containerd'
      tags:
        - runtime
    - role: crio
      when: k8s_runtime == 'crio'
      tags:
        - runtime
    - role: kubernetes
      tags:
        - k8s
    - role: nvidia
      tags:
        - gpu
        - nvidia


- name: Install Helm
  hosts:
    - controllers
  tags:
    - cluster
    - helm
  roles:
    - role: helm

- name: configure CNI
  hosts:
    - controllers
  tags:
    - cluster
    - cni
  roles:
    - role: cilium
      when:
        - k8s_cni == 'cilium'
        - inventory_hostname in k8s_controller

- name: Setup backups
  hosts: backups
  tags:
    - backups
  roles:
    - role: backups
      when: inventory_hostname in k8s_controller

- name: Deploy MetalLB
  hosts:
    - controllers
  tags:
    - lb
    - metallb
    - cluster
  roles:
    - role: metallb
      when:
        - inventory_hostname in k8s_controller

- name: Wipe ceph drives
  hosts:
    - controllers
    - workers
  tags:
    - never
    - yes-really-wipe-the-ceph-drives
  tasks:
    - include_tasks: roles/rook/tasks/format-disks.yaml

- name: Deploy Rook ceph
  hosts:
    - controllers
    - workers
  tags:
    - storage
    - rook
    - ceph
  roles:
    - role: chrony
    - role: rook

- name: Deploy cert-manager
  hosts:
    - controllers
  tags:
    - certs
    - cluster
  roles:
    - role: cert-manager
      when:
        - inventory_hostname in k8s_controller

- name: Deploy Free IPA
  hosts:
    - freeipa
  tags:
    - apps
    - ipa
  roles:
    - role: freeipa

- name: Deploy Domain config
  hosts:
    - freeipa
  tags:
    - ipa
    - config
    - domain
  connection: local
  become: false
  roles:
    - role: domain

- name: Deploy Sealed Secrets
  hosts:
    - controllers
  tags:
    - cd
    - secrets
  roles:
    - role: sealed-secrets
      when:
        - inventory_hostname in k8s_controller

- name: Deploy Keycloak realm config
  hosts:
    - controllers
  run_once: true
  tags:
    - keycloak
    - realm
    - domain
  connection: local
  become: false
  roles:
    - role: keycloak

- name: Deploy Argo CD
  hosts:
    - controllers
  tags:
    - cd
    - argo
  roles:
    - role: argo
      when:
        - inventory_hostname in k8s_controller

- name: Deploy ArgoCD controlled Apps
  hosts:
    - controllers
  tags:
    - cd
    - argo
    - argo-apps
  tasks:
    - name: Include deployment for ArgoCD Apps
      include_tasks: roles/argo/tasks/deploy-apps.yaml
      run_once: true

...
