---
# Include file: called with loop_var lldap_user
- name: "Get all LLDAP groups"
  ansible.builtin.uri:
    url: "{{ lldap_http_url }}/api/graphql"
    method: POST
    headers:
      Authorization: "Bearer {{ lldap_token }}"
      Content-Type: "application/json"
    body_format: json
    body:
      query: |
        query {
          groups {
            id
            displayName
          }
        }
    status_code: [200]
  register: all_groups_result
  delegate_to: localhost

- name: "Add {{ lldap_user.name }} to groups"
  ansible.builtin.uri:
    url: "{{ lldap_http_url }}/api/graphql"
    method: POST
    headers:
      Authorization: "Bearer {{ lldap_token }}"
      Content-Type: "application/json"
    body_format: json
    body:
      query: |
        mutation AddUserToGroup($userId: String!, $groupId: Int!) {
          addUserToGroup(userId: $userId, groupId: $groupId) {
            ok
          }
        }
      variables:
        userId: "{{ lldap_user.name }}"
        groupId: "{{ (all_groups_result.json.data.groups | selectattr('displayName', 'eq', item) | first).id }}"
    status_code: [200]
  loop: "{{ lldap_user.groups }}"
  delegate_to: localhost

