---
apiVersion: v1
kind: Secret
metadata:
  name: nextcloud-ldap-script
type: Opaque
stringData:
  ldap.sh: |-
    #!/usr/bin/env bash
    echo "Enabling ldap application"
    php occ app:enable user_ldap

    echo "Configuring ldap"
    sudo -u www-data php occ ldap:create-empty-config
    sudo -u www-data php occ ldap:set-config s01 ldapHost "ldap://ipa-01.clt.milco.casa"
    sudo -u www-data php occ ldap:set-config s01 ldapPort 389
    sudo -u www-data php occ ldap:set-config s01 ldapAgentName "uid=svc_ldap,cn=users,cn=accounts,dc=auth,dc=milco,dc=casa"
    sudo -u www-data php occ ldap:set-config s01 ldapAgentPassword $LDAP_LOOKUP_PASSWORD
    sudo -u www-data php occ ldap:set-config s01 ldapBase "dc=auth,dc=milco,dc=casa"
    sudo -u www-data php occ ldap:set-config s01 ldapUserFilter "(&(|(objectclass=posixAccount)))"
    sudo -u www-data php occ ldap:set-config s01 ldapLoginFilter "(&(&(|(objectclass=posixAccount)))(|(uid=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid))))"
    sudo -u www-data php occ ldap:set-config s01 ldapGroupFilter "(&(|(objectclass=posixGroup))(|(cn=app-nextcloud-admins)(cn=app-nextcloud-users)))"

    echo "Activating ldap config"
    sudo -u www-data php occ ldap:set-config s01 ldapConfigurationActive 1
    echo "Done"
