---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-applications
spec:
  storageClassName: cephfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: comfy
  namespace: ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: comfy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: comfy
    spec:
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Equal"
          effect: "NoSchedule"
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nvidia.com/gpu.present
                    operator: In
                    values:
                      - "true"
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - comfy
              topologyKey: "kubernetes.io/hostname"
      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - name: primary
          image: docker.io/ipenguin/ubuntu-24.04-cuda:v1.0.10
          command: ["/srv/ai/comfy/comfy.sh"]
          ports:
            - containerPort: 8188
          env:
            - name: HOME
              value: "/srv/ai"
          securityContext:
            privileged: true
            runAsUser: 1000
            runAsGroup: 1000
          resources:
            requests:
              memory: "1Gi"
            limits:
              memory: "48Gi"
          volumeMounts:
            - name: srv-ai
              mountPath: "/srv/ai"
            - name: data
              mountPath: /data
            - name: usr-lib-x86
              mountPath: /usr/lib/x86_64-linux-gnu
              readOnly: true
      volumes:
        - name: srv-ai
          persistentVolumeClaim:
            claimName: ai-applications
        - name: data
          hostPath:
            path: /data
            type: Directory
        - name: usr-lib-x86
          hostPath:
            path: /usr/lib/x86_64-linux-gnu
            type: Directory
