---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: filebrowser-secrets
  namespace: ai
spec:
  encryptedData:
    client-secret: AgAcAxjS/L6aOa4o1fkVKzUgOzZJ74y8piGH7wzGi0zaSsZ3tX7gfu9k5nev4vChCKXvxkEPFJIeU7kUjVqnIlSng6Cpe53zflWYSTPoZ7Xo+TeTas3TgNc44GKyQupJPde49tpMJI6kI2lCnL3cEJSVd6DIWlD1YD2k7ryTc4+++J1VpdulvNSKWCd6NNxS8zX8hQ0mbkvlPWv9xPG1i59iv2DyOq710TzDXh6iBXFIFUViohWCKGzCTIg551US9XndL59vzHR+SNKNoUoJJELZbNXx1pvmTrtYYsMlciyowu5Ri93D//ConyctRQ5roANLzIPEHX6JOC+BvCgsRI4f7YRjoFfh7L5TX7Q7ZYZ6q4Xzp4QudD3yIZFPWCfLsH6EeEsO1GX3kRzXLaNMKC+g5DggUZNAl2S7pdEDiebfVLXuKEUsSZMcnooGskqpV5PFZdWENdhPWekVmE8mJ+FxmS0nj24eugJlR1gE2bK7abbMnxR9BsTOBH+ieip4xZOqG+bAjNKUJmECJxqwPVL1ZFHIwDjE2wgc7b3l4ktmgHUuvE7A7OMXeFDnn31T7l9sb0zOUjQ14kvzDbvMee/PD0ClMIDJVdcvOOWT+abMrvZfoaWKTctQ0ycifUpMDgGwqGPzBUlvXPDgvwrLX+vcMMON5Y8/sEeFrpI8pnzpDGjItdiFmlc6ntkfmgDp5uEXp961eM8ZWB4yRcxwrO8EViMBBBUAd2SN7+FRL/Eg8jUP83IiuUDDfYA8M0vfJDlHAaot/BP3uUHoGRKVr7W5
  template:
    metadata:
      creationTimestamp: null
      name: filebrowser-secrets
      namespace: ai
