---
apiVersion: v1
kind: Service
metadata:
  name: comfy
spec:
  selector:
    app.kubernetes.io/name: comfy
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6
  ports:
    - protocol: TCP
      port: 8188
      targetPort: 8188
---
apiVersion: v1
kind: Service
metadata:
  name: easy
spec:
  selector:
    app.kubernetes.io/name: easy
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: comfy
spec:
  ingressClassName: traefik
  rules:
    - host: comfy.clt.milco.casa
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: comfy
                port:
                  number: 8188
    - host: easy.clt.milco.casa
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: easy
                port:
                  number: 9000
