---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ai
resources:
  - comfy.yaml
  - easy.yaml
  - filebrowser.yaml
  - filebrowser-secrets.yaml
  - ingress.yaml
  - open-webui-secrets.yaml
  - swarmui.yaml
configMapGenerator:
  - name: ai-init-scripts
    files:
      - scripts/comfy.sh
      - scripts/easy.sh
      - scripts/swarmui.sh
  - name: filebrowser-config
    files:
      - filebrowser/config.yaml
