---

- name: Deploy ArgoCD apps
  connection: local
  become: false
  ansible.builtin.command:
    cmd: kubectl apply -k argo-apps/bootstrap/
    chdir: "{{ playbook_dir }}"
  register: apply_result
  changed_when: "'created' in apply_result.stdout or 'configured' in apply_result.stdout"
...
