---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ipa-xx-data
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ipa-xx-install-options
  namespace: freeipa
data:
  ipa-server-options: |-
    placeholder
  ipa-replica-options: |-
    placeholder
  startup.sh: |-
    echo $1
    cp /tmp/$1-options /data

---
apiVersion: v1
kind: Service
metadata:
  name: ipa-xx-lb
  labels:
    app: freeipa
  annotations:
    metallb.io/loadBalancerIPs: |-
      placeholder
spec:
  type: LoadBalancer
  selector:
    app: freeipa
    id: ipa-xx
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6
  ports:
    - name: "53"
      port: 53
      targetPort: 53
    - name: "80"
      port: 80
      targetPort: 80
    - name: "443"
      port: 443
      targetPort: 443
    - name: "389"
      port: 389
      targetPort: 389
    - name: "636"
      port: 636
      targetPort: 636
    - name: "88"
      port: 88
      targetPort: 88
    - name: "464"
      port: 464
      targetPort: 464
    - name: 53-udp
      port: 53
      protocol: UDP
      targetPort: 53
    - name: 88-udp
      port: 88
      protocol: UDP
      targetPort: 88
    - name: 464-udp
      port: 464
      protocol: UDP
      targetPort: 464
    - name: "123"
      port: 123
      protocol: UDP
      targetPort: 123
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ipa-xx
spec:
  selector:
    matchLabels:
      app: freeipa
      id: ipa-xx
  serviceName: "freeipa"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: freeipa
        id: ipa-xx
    spec:
      terminationGracePeriodSeconds: 10
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - freeipa
            topologyKey: "kubernetes.io/hostname"
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - 10.1.1.1
      initContainers:
        - name: init
          image: quay.io/freeipa/freeipa-server:fedora-41-4.12.2
          command:
            - sh
            - /tmp/startup.sh
          volumeMounts:
            - name: ipa-data
              mountPath: /data
            - name: ipa-options
              mountPath: /tmp/startup.sh
              subPath: startup.sh
            - name: ipa-options
              mountPath: /tmp/ipa-server-install-options
              subPath: ipa-server-options
            - name: ipa-options
              mountPath: /tmp/ipa-replica-install-options
              subPath: ipa-replica-options
      containers:
        - name: freeipa
          image: quay.io/freeipa/freeipa-server:fedora-41-4.12.2
          readinessProbe:
            exec:
              command: ["/usr/bin/systemctl", "is-active", "--quiet", "ipa"]
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 5
          startupProbe:
            httpGet:
              path: /
              port: 80
            # NOTE: if initial installation fails, try increasing this value:
            failureThreshold: 50
            periodSeconds: 30
          args: ['ipa-server-install']
          env:
            - name: TZ
              value: "America/New_York"
            - name: IPA_SERVER_HOSTNAME
              value: "ipa-xx.clt.milco.casa"
            - name: IPA_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: freeipa
                  key: admin_password
            - name: IPA_DIRECTORY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: freeipa
                  key: directory_password
          securityContext:
            seccompProfile:
              type: Unconfined
            capabilities:
              add:
                - SYS_TIME
          stdin: true
          tty: true
          ports:
            - containerPort: 53 # dns
            - containerPort: 53 # dns
              protocol: UDP
            - containerPort: 80 # http
            - containerPort: 88 # kerberos
            - containerPort: 88 # kerberos
              protocol: UDP
            - containerPort: 123 # ntp
            - containerPort: 123 # ntp
              protocol: UDP
            - containerPort: 389 # ldap
            - containerPort: 443 # https
            - containerPort: 464 # kpasswd
            - containerPort: 464 # kpasswd
              protocol: UDP
            - containerPort: 636 # ldaps
          volumeMounts:
            - name: ipa-data
              mountPath: /data
            - name: cgroups
              mountPath: /sys/fs/cgroup
            - name: run
              mountPath: /run
            - name: run-systemd
              mountPath: /run/systemd
            - name: tmp
              mountPath: /tmp
      hostname: ipa-xx.clt.milco.casa
      volumes:
        - name: ipa-data
          persistentVolumeClaim:
            claimName: ipa-xx-data
        - name: ipa-options
          configMap:
            name: ipa-xx-install-options
        - name: cgroups
          hostPath:
            path: /sys/fs/cgroup
        - name: run
          emptyDir:
            medium: Memory
        - name: run-systemd
          emptyDir:
            medium: Memory
        - name: tmp
          emptyDir:
            medium: Memory
