---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ipa-02-data
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ipa-02-lb
  labels:
    app: freeipa
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    metallb.universe.tf/loadBalancerIPs: |-
      {{ network_services[ "ipa-02" ].ipv4 }},
      {{ network_services[ "ipa-02" ].ipv6 }}
spec:
  type: LoadBalancer
  selector:
    app: freeipa
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6
  ports:
    - name: "53"
      port: 53
      targetPort: 53
    - name: "80"
      port: 80
      targetPort: 80
    - name: "443"
      port: 443
      targetPort: 443
    - name: "389"
      port: 389
      targetPort: 389
    - name: "636"
      port: 636
      targetPort: 636
    - name: "88"
      port: 88
      targetPort: 88
    - name: "464"
      port: 464
      targetPort: 464
    - name: 53-udp
      port: 53
      protocol: UDP
      targetPort: 53
    - name: 88-udp
      port: 88
      protocol: UDP
      targetPort: 88
    - name: 464-udp
      port: 464
      protocol: UDP
      targetPort: 464
    - name: "123"
      port: 123
      protocol: UDP
      targetPort: 123
---
apiVersion: v1
kind: Secret
metadata:
  name: "ipa-02-install-secrets"
  annotations:
    argocd.argoproj.io/sync-wave: "2"
type: Opaque
stringData:
  IPA_ADMIN_PASSWORD: {{ ipa_admin_password }}
  IPA_REPLICA_OPTIONS: |-
    --unattended
    --principal=admin
    --ntp-pool=us.pool.ntp.org
    --no-host-dns
    --setup-dns
    --no-forwarders
    --skip-mem-check
    --auto-reverse
    --setup-kra
    --ssh-trust-dns
    --ip-address="{{ network_services[ 'ipa-02' ].ipv4 }}"
    --realm={{ ipa_domain | upper }}
    --domain={{ ipa_domain }}
    --server=ipa-01.{{ lan_domain }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ipa-02
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  selector:
    matchLabels:
      app: freeipa 
  serviceName: "freeipa"
  replicas: 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: freeipa
    spec:
      terminationGracePeriodSeconds: 10
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - freeipa
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: freeipa
          image: quay.io/freeipa/freeipa-server:{{ ipa_docker_os }}-{{ freeipa_version }}
          readinessProbe:
            exec:
              command: ["/usr/bin/systemctl", "is-active", "--quiet", "ipa"]
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 5
          startupProbe:
            httpGet:
              path: /
              port: 80
            # NOTE: if initial installation fails, try increasing this value:
            failureThreshold: 50
            periodSeconds: 30
          env:
            - name: TZ
              value: "{{ timezone }}"
            - name: IPA_SERVER_HOSTNAME
              value: "ipa-01.{{ lan_domain }}"
            - name: IPA_SERVER_INSTALL_OPTS
              valueFrom:
                secretKeyRef:
                  name: ipa-02-install-secrets
                  key: IPA_REPLICA_OPTIONS
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ipa-02-install-secrets
                  key: IPA_ADMIN_PASSWORD
          args: [ "ipa-replica-install" ]
          securityContext:
            seccompProfile:
              type: Unconfined
            capabilities:
              add:
                - SYS_TIME
          stdin: true
          tty: true
          ports:
            - containerPort: 53 # dns
            - containerPort: 53 # dns
              protocol: UDP
            - containerPort: 80 # http
            - containerPort: 88 # kerberos
            - containerPort: 88 # kerberos
              protocol: UDP
            - containerPort: 123 # ntp
            - containerPort: 123 # ntp
              protocol: UDP
            - containerPort: 389 # ldap
            - containerPort: 443 # https
            - containerPort: 464 # kpasswd
            - containerPort: 464 # kpasswd
              protocol: UDP
            - containerPort: 636 # ldaps
          volumeMounts:
            - name: ipa-data
              mountPath: /data
            - name: cgroups
              mountPath: /sys/fs/cgroup
            - name: run
              mountPath: /run
            - name: run-systemd
              mountPath: /run/systemd
            - name: tmp
              mountPath: /tmp
      hostname: "ipa-02.{{ lan_domain }}"
      volumes:
        - name: ipa-data
          persistentVolumeClaim:
            claimName: ipa-02-data
        - name: cgroups
          hostPath:
            path: /sys/fs/cgroup
        - name: run
          emptyDir:
            medium: Memory
        - name: run-systemd
          emptyDir:
            medium: Memory
        - name: tmp
          emptyDir:
            medium: Memory
        - name: data
