---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ipa-01-data
spec:
  storageClassName: ceph-block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: ipa-01-lb
  labels:
    app: freeipa
  annotations:
    metallb.universe.tf/loadBalancerIPs: |-
      {{ network_services[ "ipa-01" ].ipv4 }},
      {{ network_services[ "ipa-01" ].ipv6 }}
spec:
  type: LoadBalancer
  selector:
    app: freeipa
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6
  ports:
    - name: "53"
      port: 53
      targetPort: 53
    - name: "80"
      port: 80
      targetPort: 80
    - name: "443"
      port: 443
      targetPort: 443
    - name: "389"
      port: 389
      targetPort: 389
    - name: "636"
      port: 636
      targetPort: 636
    - name: "88"
      port: 88
      targetPort: 88
    - name: "464"
      port: 464
      targetPort: 464
    - name: 53-udp
      port: 53
      protocol: UDP
      targetPort: 53
    - name: 88-udp
      port: 88
      protocol: UDP
      targetPort: 88
    - name: 464-udp
      port: 464
      protocol: UDP
      targetPort: 464
    - name: "123"
      port: 123
      protocol: UDP
      targetPort: 123
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: freeipa-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - '*.milco.casa'
      secretName: star.clt.milco.casa
  rules:
    - host: ipa-01.clt.milco.casa
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ipa-01-lb
                port:
                  number: 443
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ipa-01
spec:
  selector:
    matchLabels:
      app: freeipa
  serviceName: "freeipa"
  replicas: 1
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: freeipa
    spec:
      terminationGracePeriodSeconds: 10
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - freeipa
            topologyKey: "kubernetes.io/hostname"
      containers:
        - name: freeipa
          image: quay.io/freeipa/freeipa-server:fedora-41-4.12.2
          readinessProbe:
            exec:
              command: ["/usr/bin/systemctl", "is-active", "--quiet", "ipa"]
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 5
          startupProbe:
            httpGet:
              path: /
              port: 80
            # NOTE: if initial installation fails, try increasing this value:
            failureThreshold: 50
            periodSeconds: 30
          env:
            - name: TZ
              value: "{{ timezone }}"
            - name: IPA_SERVER_HOSTNAME
              value: "ipa-01.{{ lan_domain }}"
            - name: IPA_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: freeipa
                  key: admin_password
            - name: IPA_DIRECTORY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: freeipa
                  key: directory_password
            - name: IPA_SERVER_INSTALL_OPTS
              value: placeholder
          securityContext:
            seccompProfile:
              type: Unconfined
            capabilities:
              add:
                - SYS_TIME
          stdin: true
          tty: true
          ports:
            - containerPort: 53 # dns
            - containerPort: 53 # dns
              protocol: UDP
            - containerPort: 80 # http
            - containerPort: 88 # kerberos
            - containerPort: 88 # kerberos
              protocol: UDP
            - containerPort: 123 # ntp
            - containerPort: 123 # ntp
              protocol: UDP
            - containerPort: 389 # ldap
            - containerPort: 443 # https
            - containerPort: 464 # kpasswd
            - containerPort: 464 # kpasswd
              protocol: UDP
            - containerPort: 636 # ldaps
          volumeMounts:
            - name: ipa-data
              mountPath: /data
            - name: cgroups
              mountPath: /sys/fs/cgroup
            - name: run
              mountPath: /run
            - name: run-systemd
              mountPath: /run/systemd
            - name: tmp
              mountPath: /tmp
      hostname: "ipa-01.{{ lan_domain }}"
      volumes:
        - name: ipa-data
          persistentVolumeClaim:
            claimName: ipa-01-data
        - name: cgroups
          hostPath:
            path: /sys/fs/cgroup
        - name: run
          emptyDir:
            medium: Memory
        - name: run-systemd
          emptyDir:
            medium: Memory
        - name: tmp
          emptyDir:
            medium: Memory
        - name: data
