---
global:
  storageClass: "ceph-block"

podSecurityContext:
  fsGroup: 1000

containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
#   # Add the SYS_CHROOT capability on nodes that use the container runtime cri-o.
#   # https://gitea.com/gitea/helm-gitea/issues/161
    add:
      - SYS_CHROOT
  privileged: false
  readOnlyRootFilesystem: true
  runAsGroup: 1000
  runAsNonRoot: true
  runAsUser: 1000


service:
  http:
    type: ClusterIP
    port: 3000
    ipFamilyPolicy: PreferDualStack
    ipFamilies:
      - IPv4
      - IPv6
  ssh:
    type: ClusterIP
    port: 22
    ipFamilyPolicy: PreferDualStack
    ipFamilies:
      - IPv4
      - IPv6

ingress:
  enabled: true
  className: traefik
  hosts:
    - host: git.clt.milco.casa
      paths:
        - path: /
          pathType: Prefix

persistence:
  enabled: true
  create: true
  mount: true
  claimName: gitea-shared-storage
  storageClass: cephfs
  size: 10Gi
  accessModes:
    - ReadWriteMany
  annotations:
    helm.sh/resource-policy: keep

signing:
  enabled: false
  existingSecret: ""

gitea:
  admin:
    existingSecret: gitea-secrets
  metrics:
    enabled: false
  openid:
    ENABLE_OPENID_SIGNIN: true
    ENABLE_OPENID_SIGNUP: false
  oauth:
    - name: "Homelab"
      existingSecret: gitea-secrets
      name: "homelab"
      provider: "openidConnect"
      autoDiscoverUrl: "https://sso.clt.milco.casa/realms/homelab/.well-known/openid-configuration"
      scopes: "email profile openid"  # Scopes to request from the OIDC provider

  config:
    APP_NAME: "Milco home code repo"
    RUN_MODE: prod
    server:
      DOMAIN: git.clt.milco.casa
      ROOT_URL: https://git.clt.milco.casa
      SSH_DOMAIN: git.clt.milco.casa
      SSH_PORT: 22
      SSH_LISTEN_PORT: 2222
      DISABLE_SSH: false
      OFFLINE_MODE: false
      PROTOCOL: http

  additionalConfigSources: []
  #   - secret:
  #       secretName: gitea-app-ini-oauth
  #   - configMap:
  #       name: gitea-app-ini-plaintext

  ssh:
    logLevel: "INFO"

redis-cluster:
  enabled: false
redis:
  enabled: true
  architecture: standalone
  global:
    redis:
      password: changeme
  master:
    count: 1

postgresql-ha:
  enabled: false
postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        password: giteapassword
        database: gitea
        username: gitea
      service:
        ports:
          postgresql: 5432
  primary:
    persistence:
      size: 5Gi
