---
apiVersion: v1
kind: Service
metadata:
  name: plex-share
  annotations:
    metallb.io/loadBalancerIPs: placeholder
spec:
  type: LoadBalancer
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6
  selector:
    app: plex-media-server
  ports:
    - name: plex
      port: 32400
