image:
  tag: "latest"

ingress:
  enabled: true
  ingressClassName: "traefik"

  # -- The url to use for the ingress reverse proxy to point at this pms instance
  url: "plex.clt.milco.casa"

  # -- Optional secret name to provide valid https connections
  # using an existing SSL certificate
  certificateSecret: "wildcard.milco.casa"

  # -- Custom annotations to put on the ingress resource
  annotations: {}

pms:
  storageClassName: cephfs
  configStorage: 2Gi
  gpu:
    nvidia:
      enabled: false
  requests:
    cpu: "6"
    memory: "4Gi"

rclone:
  enabled: true

  # The rclone config key must be called `rclone.conf` in the secret
  # All keys in configSecret will be available in /etc/rclone/.
  configSecret: "plex-rclone-config"

  # -- The remote drive that should be mounted using rclone
  # this must be in the form of `name:[/optional/path]`
  # this remote will be mounted at `/data/name` in the PMS container
  remotes:
    - "nextcloud:"

  readOnly: true

service:
  type: ClusterIP
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6
  ports:
    - name: plex
      port: 32400
nodeSelector:
  clt.milco.casa/node-performance: medium

extraEnv:
  # https://account.plex.tv/en/claim
  PLEX_CLAIM: "claim-kzzGpddu5wUfnewGCe_u"
  PLEX_DISABLE_HWTRANSCODE: "1"
  HOSTNAME: "plex.clt.milco.casa"
  TZ: "Americas/New_York"

extraVolumeMounts:
  - name: dev-dri
    mountPath: /dev/dri

extraVolumes:
  - name: dev-dri
    hostPath:
      path: /dev/dri
      type: Directory