image:
  tag: "latest"

ingress:
  enabled: false
  ingressClassName: "traefik"

  # -- The url to use for the ingress reverse proxy to point at this pms instance
  url: "plex.clt.milco.casa"

  # -- Optional secret name to provide valid https connections
  # using an existing SSL certificate
  certificateSecret: ""

  # -- Custom annotations to put on the ingress resource
  annotations: {}

pms:
  storageClassName: cephfs
  configStorage: 2Ti
  # NOTE: When set, 'configStorage' and 'storageClassName' are ignored.
  configExistingClaim: ""

  gpu:
    nvidia:
      enabled: true

# -- Specify your own runtime class name eg use gpu
runtimeClassName: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- If the service account token should be auto mounted
  automountServiceAccountToken: false
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

statefulSet:
  # -- Optional extra annotations to add to the service resource
  annotations: {}
  # -- Optional extra annotations to add to the pods in the statefulset
  podAnnotations: {}

service:
  type: LoadBalancer
  port: 32400
nodeSelector:
  clt.milco.casa/node-hardware: nvidia-gpu
