---

- name: Add helm repo for sealed secrets
  kubernetes.core.helm_repository:
    name: sealed-secrets
    repo_url: https://bitnami-labs.github.io/sealed-secrets
    state: present

- name: Create Sealed Secret TLS Key
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'sealed-secrets-key.yaml.j2') | from_yaml }}"

- name: Install sealed-secrets
  kubernetes.core.helm:
    name: sealed-secrets
    chart_version: '{{ sealed_secrets_version }}'
    chart_ref: sealed-secrets/sealed-secrets
    release_namespace: sealed-secrets
    create_namespace: true
    update_repo_cache: true
