---
# handlers file for kubernetes

- name: restart sysctl
  ansible.builtin.service:
    name: sysctl
    state: restarted

- name: restart ubuntu sysctl
  ansible.builtin.service:
    name: systemd-sysctl
    state: restarted

- name: restart networking
  ansible.builtin.service:
    name: systemd-networkd
    state: restarted
