---

all:
  children:
    metal:
      children:
        controllers:
          hosts:
            c1.clt.milco.casa:
            c2.clt.milco.casa:
            c3.clt.milco.casa:
        workers:
          hosts:
            w1.clt.milco.casa:
            w2.clt.milco.casa:
            w3.clt.milco.casa:
            w4.clt.milco.casa:
    openwrt:
      children:
        router:
          hosts:
            r.milco.casa:

backups:
  hosts:
    c1.clt.milco.casa:

#
# In a production cluster the mons should be different from the osds.
#
ceph:
  children:
    ceph_mons:
      hosts:
        c1.clt.milco.casa:
        c2.clt.milco.casa:
        c3.clt.milco.casa:
    ceph_osds:
      hosts:
        c1.clt.milco.casa:
        c2.clt.milco.casa:
        c3.clt.milco.casa:
        w1.clt.milco.casa:
        w2.clt.milco.casa:
        w3.clt.milco.casa:

apps:
  children:
    freeipa:
      hosts:
        c1.clt.milco.casa:
    gitea:
      hosts:
        c1.clt.milco.casa:
    ingress:
      hosts:
        c1.clt.milco.casa:

workstations:
  hosts:
    localhost:


remote:
  vars:
    #    ansible_ssh_common_args: '-o ProxyCommand="ssh -p 2221 -W %h:%p -q {{ remote_host }}"'
  children:
    controllers:
      hosts:
        c1.clt.milco.casa:
          ansible_host: 10.1.1.10
        c2.clt.milco.casa:
          ansible_host: 10.1.1.11
        c3.clt.milco.casa:
          ansible_host: 10.1.1.12
    workers:
      hosts:
        w1.clt.milco.casa:
          ansible_host: 10.1.1.13
        w2.clt.milco.casa:
          ansible_host: 10.1.1.14
        w3.clt.milco.casa:
          ansible_host: 10.1.1.15
        w4.clt.milco.casa:
          ansible_host: 10.1.1.16

