---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dig
  namespace: argocd
data:
  requestTimeout: "60"
  baseUrl: "http://dig.kube-utils.svc.cluster.local:8000"
  token: "$plugin.myplugin.token"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ipa-install-options
data:
  ipa-server-options: |-
    placeholder
  ipa-replica-options: |-
    placeholder
  startup.sh: |-
    echo $1
    cp /tmp/$1-options /data
