#!/bin/bash
# Install (on first run or version change) and launch ComfyUI on the shared ai-applications volume.
# The ai-base image has no python, so uv bootstraps a standalone interpreter and venv on the
# volume. Bump COMFY_VERSION to upgrade; custom_nodes in the checkout are kept.
# Models live in MODELS_DIR (shared with the other AI apps), registered via extra_model_paths.yaml.
# Input and output images live in DATA_DIR, outside the checkout.
set -euo pipefail

APP_DIR="${APP_DIR:-/srv/ai/comfy}"
COMFY_VERSION="${COMFY_VERSION:-v0.38.0}"
COMFY_REPO="${COMFY_REPO:-https://github.com/comfyanonymous/ComfyUI.git}"
PYTHON_VERSION="${PYTHON_VERSION:-3.13}"
# cu130 needs driver >= 580 and is what upstream requires for RTX 20 series and newer
TORCH_BACKEND="${TORCH_BACKEND:-cu130}"
# not COMFY_PORT: kubernetes sets that to tcp://<ip>:8188 for the comfy service
LISTEN_PORT="${LISTEN_PORT:-8188}"
MODELS_DIR="${MODELS_DIR:-/srv/models}"
DATA_DIR="${DATA_DIR:-/srv/data/comfyui}"

SRC_DIR="$APP_DIR/ComfyUI"
VENV_DIR="$APP_DIR/venv-py$PYTHON_VERSION"
STAMP="$VENV_DIR/.comfy-version"
MODEL_PATHS="$APP_DIR/extra_model_paths.yaml"
# shared model folders, named the way ComfyUI names them
MODEL_TYPES=(checkpoints vae loras embeddings controlnet upscale_models clip_vision text_encoders
  diffusion_models hypernetworks)

export UV_INSTALL_DIR="$APP_DIR/bin"
export UV_PYTHON_INSTALL_DIR="$APP_DIR/python"
export UV_CACHE_DIR="$APP_DIR/.cache/uv"
# cache and venv live on cephfs; don't rely on hardlinks
export UV_LINK_MODE=copy
export PATH="$UV_INSTALL_DIR:$PATH"

mkdir -p "$APP_DIR"
cd "$APP_DIR"

if ! command -v uv >/dev/null; then
  echo "Installing uv into $UV_INSTALL_DIR"
  curl -fsSL --retry 3 https://astral.sh/uv/install.sh | env UV_NO_MODIFY_PATH=1 sh
fi

# Clone on first run, otherwise move the existing checkout to the pinned tag
if [ ! -d "$SRC_DIR/.git" ]; then
  echo "Cloning ComfyUI $COMFY_VERSION into $SRC_DIR"
  git clone --branch "$COMFY_VERSION" "$COMFY_REPO" "$SRC_DIR"
elif [ "$(git -C "$SRC_DIR" describe --tags --exact-match 2>/dev/null || true)" != "$COMFY_VERSION" ]; then
  echo "Updating ComfyUI checkout to $COMFY_VERSION"
  git -C "$SRC_DIR" fetch --tags --force origin
  git -C "$SRC_DIR" checkout --force "$COMFY_VERSION"
fi

if [ ! -x "$VENV_DIR/bin/python" ]; then
  uv venv --python "$PYTHON_VERSION" "$VENV_DIR"
fi

# (Re)install dependencies only when the pinned version changes
if [ "$(cat "$STAMP" 2>/dev/null || true)" != "$COMFY_VERSION" ]; then
  echo "Installing ComfyUI $COMFY_VERSION dependencies"
  export VIRTUAL_ENV="$VENV_DIR"
  uv pip install --torch-backend "$TORCH_BACKEND" torch torchvision torchaudio \
    -r "$SRC_DIR/requirements.txt" -r "$SRC_DIR/manager_requirements.txt"
  echo "$COMFY_VERSION" > "$STAMP"
fi

"$VENV_DIR/bin/python" -c 'import torch; print("torch", torch.__version__, "cuda:", torch.cuda.is_available())'

# Register the shared models dir; is_default makes ComfyUI-Manager download into it too
{
  echo "# generated by comfy.sh on every start; edit the script, not this file"
  echo "shared:"
  echo "  base_path: $MODELS_DIR"
  echo "  is_default: true"
  for t in "${MODEL_TYPES[@]}"; do
    mkdir -p "$MODELS_DIR/$t"
    echo "  $t: $t"
  done
} > "$MODEL_PATHS"

# Move models downloaded into the checkout over to the shared dir (clip and unet are ComfyUI's
# legacy names for text_encoders and diffusion_models). -n never overwrites a shared file (and
# exits non-zero when it skips one, hence the || true), so a name clash is left in place; the
# put_*_here placeholders are tracked by git and stay.
for t in "${MODEL_TYPES[@]}" clip:text_encoders unet:diffusion_models; do
  src="$SRC_DIR/models/${t%%:*}"
  [ -d "$src" ] || continue
  find "$src" -mindepth 1 -maxdepth 1 ! -name 'put_*_here' -exec mv -n -t "$MODELS_DIR/${t##*:}" {} + || true
done

# Same for input/output images left in the checkout from before DATA_DIR existed; the
# placeholder files tracked by git stay
for d in input output; do
  mkdir -p "$DATA_DIR/$d"
  [ -d "$SRC_DIR/$d" ] || continue
  find "$SRC_DIR/$d" -mindepth 1 -maxdepth 1 ! -name '*_here' ! -name example.png \
    -exec mv -n -t "$DATA_DIR/$d" {} + || true
done

cd "$SRC_DIR"
# bind both families: the comfy service is dual-stack and asyncio makes a "::" socket IPv6-only
exec "$VENV_DIR/bin/python" main.py --listen 0.0.0.0,:: --port "$LISTEN_PORT" --enable-manager \
  --extra-model-paths-config "$MODEL_PATHS" \
  --input-directory "$DATA_DIR/input" --output-directory "$DATA_DIR/output"
