---

- name: create kubeadm init config
  ansible.builtin.template:
    src: kubeadm.yaml.j2
    dest: "{{ _kubeadm_config }}"
  vars:
    host_ipv4: "{{ hosts | json_query('[?name==`' ~ ansible_hostname ~ '`].ipv4') | first }}"
    host_ipv6: "{{ ipv6_network }}::{{ hosts | json_query('[?name==`' ~ ansible_hostname ~ '`].hostid') | first }}"
  register: kube_config

- name: kubeadm init
  command: kubeadm init --config /root/kubeadm.yaml --skip-phases=addon/kube-proxy
  when: kube_config.changed

- name: create .kube config dir
  become: yes
  ansible.builtin.file:
    path: "/root/.kube"
    state: directory
    owner: root
    group: root
    mode: 0700

- name: copy k8 admin to user dir
  become: yes
  ansible.builtin.copy:
    remote_src: yes
    src: /etc/kubernetes/admin.conf
    dest: "/root/.kube/config"
    owner: root
    group: root
    mode: 0600

- name: should we clear the taint for controller nodes?
  ansible.builtin.set_fact:
    _k8s_master_node_schedule_taint: absent
  when: k8s_master_can_run_pods | bool

- name: Primary - Can master node run pods {{ _k8s_master_node_schedule_taint }}
  kubernetes.core.k8s_taint:
    state: "{{ _k8s_master_node_schedule_taint }}"
    name: "{{ inventory_hostname }}"
    taints:
    - effect: NoSchedule
      key: "node-role.kubernetes.io/control-plane"
