---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: concourse
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters: {}
  template:
    metadata:
      name: concourse
    spec:
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
      project: concourse
      destination:
        namespace: concourse
        server: https://kubernetes.default.svc
      sources:
        - repoURL: https://github.com/ipenguin/bare-metal-kubernetes.git
          path: argo-apps/apps/concourse
          targetRevision: master
        - repoURL: 'https://concourse-charts.storage.googleapis.com/'
          chart: concourse
          targetRevision: 18.1.1
          helm:
            valueFiles:
              - '$valuesSrc/argo-apps/apps/concourse/values.yaml'
        - repoURL: https://github.com/ipenguin/bare-metal-kubernetes.git
          targetRevision: master
          ref: valuesSrc