---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: freeipa-utils
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters: {}
  template:
    metadata:
      name: 'freeipa-utils'
    spec:
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
      project: freeipa
      destination:
        namespace: freeipa
        server: https://kubernetes.default.svc
      source:
        repoURL: https://github.com/ipenguin/bare-metal-kubernetes.git
        path: argo-apps/apps/freeipa-utils
        targetRevision: HEAD
