---
apiVersion: v1
kind: ConfigMap
metadata:
  name: get-ip
  namespace: argocd
data:
  requestTimeout: "60"
  baseUrl: "http://dns-lookup-svc.freeipa.svc.cluster.local:8000"
  token: "$plugin.myplugin.token"
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: freeipa
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - merge:
        mergeKeys:
          - host
        generators:
          - list:
              elements:
                - host: ipa-01
                  command: ipa-server-install
                  flags: |-
                    --unattended
                    --realm=AUTH.MILCO.CASA
                    --domain=auth.milco.casa
                    --ds-password=$IPA_DIRECTORY_PASSWORD
                    --admin-password=$IPA_ADMIN_PASSWORD
                    --ntp-pool=us.pool.ntp.org
                    --no-host-dns
                    --setup-dns
                    --zonemgr=user@example.com
                    --no-forwarders
                    --skip-mem-check
                    --auto-reverse
                    --setup-kra
                    --ssh-trust-dns
                    --ip-address=placeholder
                - host: ipa-02
                  command: ipa-replica-install
                  flags: |-
                    --unattended
                    --realm=AUTH.MILCO.CASA
                    --domain=auth.milco.casa
                    --principal=admin
                    --ntp-pool=us.pool.ntp.org
                    --no-host-dns
                    --setup-dns
                    --no-forwarders
                    --skip-mem-check
                    --auto-reverse
                    --setup-kra
                    --ssh-trust-dns
                    --ip-address=placeholder
                    --server=ipa-01.clt.milco.casa

          - plugin:
              configMapRef:
                name: get-ip
                key: get-ip.yaml
              input:
                parameters:
                  hostname: '{{ .host }}.clt.milco.casa'

  template:
    metadata:
      name: freeipa
    spec:
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
      project: freeipa
      destination:
        namespace: freeipa
        server: https://kubernetes.default.svc
      source:
        repoURL: https://github.com/ipenguin/bare-metal-kubernetes.git
        path: argo-apps/apps/freeipa
        targetRevision: HEAD
        kustomize:
          patches:
            - target:
                kind: PersistentVolumeClaim
                name: ipa-data
              patch: |-
                - op: replace
                  path: /metadata/name
                  value: {{ .host }}-data
            - target:
                kind: Service
                name: ipa-lb
              patch: |-
                - op: replace
                  path: /metadata/name
                  value: {{ .host }}-lb
                - op: replace
                  path: /metadata/annotations/metallb.universe.tf~1loadBalancerIPs
                  value: |-
                    {{ . | toJson }}
            - target:
                kind: StatefulSet
                name: ipa
              patch: |-
                - op: replace
                  path: /metadata/name
                  value: {{ .host }}
                - op: replace
                  path: /spec/template/spec/containers/0/env/4/value
                  value: {{ .flags }}
                - op: replace
                  path: /spec/template/spec/containers/0/command
                  value: [ "{{ .command }}" ]

