---
apiVersion: v1
kind: ConfigMap
metadata:
  name: get-ip
  namespace: argocd
data:
  requestTimeout: "60"
  baseUrl: "http://dns-lookup-svc.freeipa.svc.cluster.local:8000"
  token: "$plugin.myplugin.token"
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: freeipa
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - plugin:
        configMapRef:
          name: get-ip
          key: get-ip.yaml
        input:
          parameters:
            hostname: 'ipa-01.clt.milco.casa'
    - git:
        repoURL: https://github.com/ipenguin/bare-metal-kubernetes.git
        revision: HEAD
        files:
          - path: "argo-apps/values/main.yaml"

  template:
    metadata:
      name: freeipa
    spec:
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
      project: freeipa
      destination:
        namespace: freeipa
        server: https://kubernetes.default.svc
      source:
        repoURL: https://github.com/ipenguin/bare-metal-kubernetes.git
        path: argo-apps/apps/freeipa
        targetRevision: HEAD
        kustomize:
          patches:
            - target:
                kind: Service
                name: ipa-01-lb
              patch: |-
                - op: replace
                  path: /metadata/annotations/metallb.universe.tf~1loadBalancerIPs
                  value: |-
                    {{ .ipv4_address }},
                    {{ .ipv6_address }}
            - target:
                kind: StatefulSet
                name: ipa-01
              patch: |-
                - op: replace
                  path: /spec/template/spec/containers/0/env/4/value
                  value: |-
                    --unattended
                    --realm=AUTH.MILCO.CASA
                    --domain=auth.milco.casa
                    --ds-password=$IPA_DIRECTORY_PASSWORD
                    --admin-password=$IPA_ADMIN_PASSWORD
                    --ntp-pool=us.pool.ntp.org
                    --no-host-dns
                    --setup-dns
                    --zonemgr=user@example.com
                    --no-forwarders
                    --skip-mem-check
                    --auto-reverse
                    --setup-kra
                    --ssh-trust-dns
                    --ip-address='{{ .ipv4_address }}'
            - target:
                kind: StatefulSet
                name: ipa-02
              patch: |-
                - op: replace
                  path: /spec/template/spec/containers/0/env/3/value
                  value: |-
                    --unattended
                    --realm=AUTH.MILCO.CASA
                    --domain=auth.milco.casa
                    --principal=admin
                    --ntp-pool=us.pool.ntp.org
                    --no-host-dns
                    --setup-dns
                    --no-forwarders
                    --skip-mem-check
                    --auto-reverse
                    --setup-kra
                    --ssh-trust-dns
                    --ip-address='10.1.1.24'
                    --server=ipa-01.clt.milco.casa
