---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: freeipa
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - host: ipa-01
                  command: ipa-server-install
                - host: ipa-02
                  command: ipa-replica-install
          - plugin:
              configMapRef:
                name: get-ip
              input:
                parameters:
                  hostname: '{{ .host }}.clt.milco.casa'
  template:
    metadata:
      name: '{{ .host }}'
    spec:
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - Confirm=true
        syncWave: "2"
      project: freeipa
      destination:
        namespace: freeipa
        server: https://kubernetes.default.svc
      source:
        repoURL: https://github.com/ipenguin/bare-metal-kubernetes.git
        path: argo-apps/apps/freeipa
        targetRevision: HEAD
        kustomize:
          patches:
            - target:
                kind: ConfigMap
                name: ipa-xx-install-options
              patch: |-
                - op: replace
                  path: /metadata/name
                  value: {{ .host }}-install-options
                - op: replace
                  path: /data/ipa-server-options
                  value: |-
                    --unattended
                    --realm=AUTH.MILCO.CASA
                    --domain=auth.milco.casa
                    --ds-password=$IPA_DIRECTORY_PASSWORD
                    --admin-password=$IPA_ADMIN_PASSWORD
                    --ntp-pool=us.pool.ntp.org
                    --no-host-dns
                    --setup-dns
                    --zonemgr=admin@milco.casa
                    --no-forwarders
                    --skip-mem-check
                    --auto-reverse
                    --setup-kra
                    --ssh-trust-dns
                    --ip-address={{ .ipv4_address }}
                    --ip-address={{ .ipv6_address }}
                - op: replace
                  path: /data/ipa-replica-options
                  value: |-
                    --unattended
                    --realm=AUTH.MILCO.CASA
                    --domain=auth.milco.casa
                    --principal=admin
                    --password=$IPA_ADMIN_PASSWORD
                    --ntp-pool=us.pool.ntp.org
                    --no-host-dns
                    --setup-dns
                    --no-forwarders
                    --skip-mem-check
                    --auto-reverse
                    --setup-ca
                    --setup-kra
                    --ssh-trust-dns
                    --ip-address={{ .ipv4_address }}
                    --ip-address={{ .ipv6_address }}
                    --server=ipa-01.clt.milco.casa
            - target:
                kind: PersistentVolumeClaim
                name: ipa-xx-data
              patch: |-
                - op: replace
                  path: /metadata/name
                  value: {{ .host }}-data
            - target:
                kind: Service
                name: ipa-xx-lb
              patch: |-
                - op: replace
                  path: /metadata/name
                  value: {{ .host }}-lb
                - op: replace
                  path: /spec/selector/id
                  value: {{ .host }}
                - op: replace
                  path: /metadata/annotations/metallb.io~1loadBalancerIPs
                  value: {{ .ipv4_address }},{{ .ipv6_address }}
            - target:
                kind: StatefulSet
                name: ipa-xx
              patch: |-
                - op: replace
                  path: /metadata/name
                  value: {{ .host }}
                - op: replace
                  path: /spec/selector/matchLabels/id
                  value: {{ .host }}
                - op: replace
                  path: /spec/template/metadata/labels/id
                  value: {{ .host }}
                - op: replace
                  path: /spec/template/spec/containers/0/env/1/value
                  value: {{ .host }}.clt.milco.casa
                - op: replace
                  path: /spec/template/spec/hostname
                  value: {{ .host }}.clt.milco.casa
                - op: replace
                  path: /spec/template/spec/initContainers/0/args
                  value: [ "{{ .command }}" ]
                - op: replace
                  path: /spec/template/spec/containers/0/args
                  value: [ "{{ .command }}" ]
                - op: replace
                  path: /spec/template/spec/volumes/0/persistentVolumeClaim/claimName
                  value: {{ .host }}-data
                - op: replace
                  path: /spec/template/spec/volumes/1/configMap/name
                  value: {{ .host }}-install-options
