---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gitea
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - host: gitea
          - plugin:
              configMapRef:
                name: dig
              input:
                parameters:
                  hostname: '{{ .host }}.clt.milco.casa'
  template:
    metadata:
      name: gitea
    spec:
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - Confirm=true
      project: gitea
      destination:
        namespace: gitea
        server: https://kubernetes.default.svc
      sources:
        - repoURL: https://github.com/ipenguin/bare-metal-kubernetes.git
          targetRevision: master
          path: argo-apps/apps/gitea
        - repoURL: https://github.com/ipenguin/bare-metal-kubernetes.git
          targetRevision: master
          ref: valuesSrc
        - repoURL: 'https://dl.gitea.io/charts/'
          chart: gitea
          targetRevision: 11.0.0
          helm:
            valueFiles:
              - '$valuesSrc/argo-apps/apps/gitea/values.yaml'
