---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: keycloak
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - host: sso
          - plugin:
              configMapRef:
                name: dig
              input:
                parameters:
                  hostname: '{{ .host }}.clt.milco.casa'
  template:
    metadata:
      name: keycloak
    spec:
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - Confirm=true
      project: keycloak
      destination:
        namespace: keycloak
        server: https://kubernetes.default.svc
      sources:
        - repoURL: https://github.com/ipenguin/bare-metal-kubernetes.git
          targetRevision: master
          path: argo-apps/apps/keycloak
        - repoURL: https://github.com/ipenguin/bare-metal-kubernetes.git
          targetRevision: master
          ref: valuesSrc
        - repoURL: 'registry-1.docker.io/bitnamicharts'
          chart: keycloak
          path: keycloak
          targetRevision: 24.5.2
          helm:
            valueFiles:
              - '$valuesSrc/argo-apps/apps/keycloak/values.yaml'
