
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: kubernetes-reflector
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
        - cluster: prod 
  template:
    metadata:
      name: 'kubernetes-reflector-{{ .cluster }}'
    spec:
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
      project: kubernetes-reflector
      destination:
        namespace: cert-manager
        server: https://kubernetes.default.svc
      sources:
        - repoURL: 'https://emberstack.github.io/helm-charts'
          chart: emberstack/reflector
          targetRevision: 9.0.313
