---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: minio
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - host: minio
  template:
    metadata:
      name: minio
    spec:
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - Confirm=true
      project: minio
      destination:
        namespace: minio
        server: https://kubernetes.default.svc
      sources:
        - repoURL: https://github.com/ipenguin/bare-metal-kubernetes.git
          targetRevision: master
          path: argo-apps/apps/minio
          kustomize:
            patches:
              - target:
                  kind: Service
                  name: minio
                patch: |-
                  - op: replace
                    path: /spec/ipFamilyPolicy
                    value: PreferDualStack
                  - op: add
                    path: /spec/ipFamilies/-
                    value: IPv6
              - target:
                  kind: Service
                  name: minio-console
                patch: |-
                  - op: replace
                    path: /spec/ipFamilyPolicy
                    value: PreferDualStack
                  - op: add
                    path: /spec/ipFamilies/-
                    value: IPv6
        - repoURL: https://github.com/ipenguin/bare-metal-kubernetes.git
          targetRevision: master
          ref: valuesSrc
        - repoURL: 'registry-1.docker.io/bitnamicharts'
          chart: minio
          targetRevision: 17.0.21
          helm:
            valueFiles:
              - '$valuesSrc/argo-apps/apps/minio/values.yaml'