---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: plex
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - host: plex
          - plugin:
              configMapRef:
                name: dig
              input:
                parameters:
                  hostname: '{{ .host }}.clt.milco.casa'
                  secondary: 'plex-svc.clt.milco.casa'
  template:
    metadata:
      name: plex
    spec:
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - Confirm=true
      project: plex
      destination:
        namespace: plex
        server: https://kubernetes.default.svc
      sources:
        - repoURL: https://github.com/ipenguin/bare-metal-kubernetes.git
          targetRevision: master
          path: argo-apps/apps/plex
          kustomize:
            patches:
              - target:
                  kind: Service
                  name: "plex-share"
                patch: |-
                  - op: replace
                    path: /metadata/annotations/metallb.io~1loadBalancerIPs
                    value: {{ .secondary_ipv4 }},{{ .secondary_ipv6 }}
        - repoURL: https://github.com/ipenguin/bare-metal-kubernetes.git
          targetRevision: master
          ref: valuesSrc
        - repoURL: 'https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages'
          chart: plex-media-server
          targetRevision: 0.9.1
          helm:
            valueFiles:
              - '$valuesSrc/argo-apps/apps/plex/values.yaml'
            values: |-
              service:
                annotations:
                  metallb.io/loadBalancerIPs: {{ .ipv4_address }},{{ .ipv6_address }}