---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: plex
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - host: plex
          - plugin:
              configMapRef:
                name: dig
              input:
                parameters:
                  hostname: '{{ .host }}.clt.milco.casa'
  template:
    metadata:
      name: plex
    spec:
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - Confirm=true
      project: plex
      destination:
        namespace: plex
        server: https://kubernetes.default.svc
      sources:
        - repoURL: 'https://raw.githubusercontent.com/plexinc/pms-docker/gh-pages'
          chart: plex
          targetRevision: 0.8.0
          helm:
            valueFiles:
              - '$valuesSrc/argo-apps/apps/plex/values.yaml'
            values: |-
              service:
                annotations:
                  metallb.io/loadBalancerIPs: {{ .ipv4_address }},{{ .ipv6_address }}
