---

k8s_runtime: crio
k8s_cni: cilium

k8s_master_can_run_pods: no

k8s_cluster_name: homelab

k8s_controller: "{{ groups['controllers'] | first }}"
k8s_api_endpoint: "kube-api.{{ lan_domain }}"

k8s_pod_network:
  ipv4: 10.200.0.0/16
  ipv6: "{{ ipv6_network }}:dead::/80"
k8s_service_network:
  ipv4: 172.16.0.0/12
  ipv6: "{{ ipv6_network }}:face:1e55::/112"

#
# This will create a secret called admin-[username] in kube-system namespace.
# It will contain the ca.crt as is, and your token base64 encoded.
#
k8s_admin_users:
  - bmilco
