---
replicaCount: 1

env:
  LLDAP_LDAP_PORT: "3890"
  LLDAP_HTTP_PORT: "17170"
  LLDAP_SMTP_OPTIONS__ENABLE_PASSWORD_RESET: "false"
  LLDAP_IGNORED_USER_ATTRIBUTES: '["krb5principalname","pwdchangedtime"]'

lldap:
  baseDN: "dc=milco,dc=casa"
  secretName: lldap-secrets
  jwtSecretKey: LLDAP_JWT_SECRET
  ldapUserPassKey: LLDAP_LDAP_USER_PASS
  keySeedKey: LLDAP_KEY_SEED

persistence:
  enabled: true
  storageClass: "ceph-block"
  accessMode: ReadWriteOnce
  size: 1Gi

podSecurityContext:
  fsGroup: 10001

service:
  http:
    type: ClusterIP
    port: 17170
  ldap:
    type: ClusterIP
    port: 3890

ingress:
  enabled: true
  className: "traefik"
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "lldap.clt.milco.casa"
  hosts:
    - host: lldap.clt.milco.casa
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: wildcard.milco.casa
      hosts:
        - lldap.clt.milco.casa
