- name: Include drive info
  include_tasks: get-drives.yaml

- name: Install utils
  ansible.builtin.apt:
    name:
      - ceph-volume
    state: present

- name: Zap ceph lvm
  command: "ceph-volume lvm zap --destroy /dev/{{ item.name }}"
  delegate_to: "{{ inventory_hostname }}"
  loop: "{{ host_matched_devices }}"

- name: Wipe drive
  command: "blkdiscard /dev/{{ item.name }}"
  delegate_to: "{{ inventory_hostname }}"
  loop: "{{ host_matched_devices }}"

- name: Delete rook configuration folder
  file:
    path: "/var/lib/rook"
    state: absent
  delegate_to: "{{ inventory_hostname }}"
  ignore_errors: yes
