image:
  repository: nextcloud
  flavor: fpm
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  ingressClassName: "traefik"
  tls:
    - secretName: wildcard.clt.milco.casa
      hosts:
        - nextcloud.clt.milco.casa

phpClientHttpsFix:
  enabled: false
  protocol: https

nextcloud:
  host: nextcloud.clt.milco.casa
  existingSecret:
    enabled: true
    secretName: nextcloud-secrets
    usernameKey: admin_user
    passwordKey: admin_password
  containerPort: 8080
  datadir: /var/www/html/data
  trustedDomains:
    - nextcloud.clt.milco.casa
    - nextcloud.nextcloud.svc.cluster.local
    - nextcloud.nextcloud.svc
  ## SMTP configuration
  mail:
    enabled: false
  ## Primary ObjectStore options
  objectStore:
    s3:
      enabled: true
      ssl: true
      port: "443"
      region: "us-east-1"
      autoCreate: true
      usePathStyle: true
      existingSecret: "nextcloud-data"
      secretKeys:
        accessKey: "AWS_ACCESS_KEY_ID"
        secretKey: "AWS_SECRET_ACCESS_KEY"

nginx:
  enabled: true
  image:
    repository: nginx
    tag: alpine
    pullPolicy: IfNotPresent
  containerPort: 8080
  ipFamilies:
    - IPv4
    - IPv6

internalDatabase:
  enabled: false
externalDatabase:
  enabled: true
  type: postgresql
  host: "nextcloud-postgresql-0"
  existingSecret:
    enabled: true
    secretName: nextcloud-secrets
    usernameKey: db_username
    passwordKey: db_password
    # hostKey: db-hostname-or-ip
    # databaseKey: db-name

postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        username: nextcloud
        existingSecret: "nextcloud-secrets"
        secretKeys:
          adminPasswordKey: "db_password"
          userPasswordKey: "db_password"
          replicationPasswordKey: "db_replication_password"
  primary:
    persistence:
      enabled: true

collabora:
  enabled: false
cronjob:
  enabled: true

persistence:
  enabled: true
  annotations: {}
  storageClass: "cephfs"
  accessMode: ReadWriteMany
  size: 8Gi

hpa:
  enabled: true
  cputhreshold: 60
  minPods: 1
  maxPods: 7

metrics:
  enabled: false

rbac:
  enabled: true
  serviceaccount:
    create: true
    name: nextcloud-serviceaccount
