image:
  repository: nextcloud
  flavor: fpm
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: nextcloud-nextcloud-redirectregex@kubernetescrd,nextcloud-nextcloud-headers@kubernetescrd
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6

phpClientHttpsFix:
  enabled: false
  protocol: https

nextcloud:
  host: nextcloud.clt.milco.casa
  extraEnv:
    - name: TRUSTED_PROXIES
      value: "10.200.0.0/16 172.16.0.0/12"
    - name: OVERWRITECLIURL
      value: "https://nextcloud.clt.milco.casa"
    - name: OVERWRITEPROTOCOL
      value: "https"
    - name: OVERWRITEHOST
      value: "nextcloud.clt.milco.casa"
    - name: NEXTCLOUD_TRUSTED_DOMAINS
      value: "nextcloud.clt.milco.casa"
    - name: NEXTCLOUD_ADMIN_USER
      valueFrom:
        secretKeyRef:
          name: nextcloud-secrets
          key: admin_username
    - name: NEXTCLOUD_ADMIN_PASSWORD
      valueFrom:
        secretKeyRef:
          name: nextcloud-secrets
          key: admin_password
    # Database connection variables
    - name: POSTGRES_HOST
      value: "nextcloud-prod-postgresql"  # Adjust this to match your PostgreSQL service name
    - name: POSTGRES_DB
      value: "nextcloud"
    - name: POSTGRES_USER
      value: "nextcloud"
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: nextcloud-secrets
          key: db_user_password
    # - name: NEXTCLOUD_CONFIG_KEYCLOAK_CLIENT_SECRET
    #   valueFrom:
    #     secretKeyRef:
    #       name: nextcloud-secrets
    #       key: client-secret

  existingSecret:
    enabled: true
    secretName: nextcloud-secrets
    usernameKey: admin_username
    passwordKey: admin_password
  containerPort: 8080
  datadir: /var/www/html/data
  trustedDomains:
    - nextcloud.clt.milco.casa
    - nextcloud.nextcloud.svc.cluster.local
    - nextcloud.nextcloud.svc
  ## SMTP configuration
  mail:
    enabled: false
  ## Primary ObjectStore options
  objectStore:
    s3:
      enabled: false

  # configs:
  #   keycloak-oidc.config.php: |-
  #     <?php
  #     $CONFIG = array (
  #       # Disable regular user registration
  #       'allow_user_to_change_display_name' => false,
  #       'lost_password_link' => 'disabled',

  #       # OIDC provider settings for Keycloak
  #       'user_oidc' => array(
  #         'single_logout' => true,
  #         'auto_provision' => true,
  #         'soft_auto_provision' => true,
  #       ),

  #       # Example attribute mapping (uncomment and adjust as needed):
  #       # 'user_oidc' => array(
  #       #   'provider-params' => array(
  #       #     'keycloak' => array(
  #       #       'displayNameMapping' => 'name',
  #       #       'mailMapping' => 'email',
  #       #       'groupMapping' => 'groups',
  #       #       'quotaMapping' => 'nextcloud_quota',
  #       #       'uidMapping' => 'preferred_username',
  #       #     ),
  #       #   ),
  #       # ),
  #     );

  #   config.php: |-
  #     <?php
  #     $CONFIG = array (
  #       'allow_user_to_change_display_name' => false,
  #       'lost_password_link' => 'disabled',
  #       'oidc_login_provider_url' => 'https://sso.clt.milco.casa/realms/homelab',
  #       'oidc_login_client_id' => 'nextcloud',
  #       'oidc_login_client_secret' => '{{ .Values.keycloakClientSecret }}',
  #       'oidc_login_auto_redirect' => false,
  #       'oidc_login_logout_url' => 'https://sso.clt.milco.casa/realms/homelab/protocol/openid-connect/logout?redirect_uri=https://nextcloud.clt.milco.casa/',
  #       'oidc_login_default_quota' => '1000000000',
  #       'oidc_login_button_text' => 'Login with Homelab',
  #       'oidc_login_attributes' => array (
  #         'id' => 'preferred_username',
  #         'name' => 'name',
  #         'mail' => 'email',
  #         'groups' => 'ownCloudGroups',
  #       ),
  #       'oidc_login_scope' => 'openid profile email',
  #       'overwriteprotocol' => 'https',
  #       'overwrite.cli.url' => 'https://nextcloud.clt.milco.casa',
  #     );

nginx:
  enabled: true
  image:
    repository: nginx
    tag: alpine
    pullPolicy: IfNotPresent
  containerPort: 8080
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6

internalDatabase:
  enabled: false
externalDatabase:
  enabled: true
  type: postgresql
  host: "nextcloud-postgresql-0"
  existingSecret:
    enabled: true
    secretName: nextcloud-secrets
    usernameKey: db_username
    passwordKey: db_password

postgresql:
  enabled: true
  auth:
    username: nextcloud
    database: nextcloud
    existingSecret: nextcloud-secrets
    secretKeys:
      adminPasswordKey: db_password
      userPasswordKey: db_user_password
  primary:
    initdb:
      scriptsSecret: nextcloud-secrets
    persistence:
      enabled: true
      size: 10Gi

collabora:
  enabled: false
cronjob:
  enabled: true

service:
  type: ClusterIP
  port: 8080
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6

persistence:
  enabled: true
  storageClass: "cephfs"
  accessMode: ReadWriteMany
  size: 8Gi
  nextcloudData:
    enabled: true
    existingClaim: nextcloud-data

resources:
  limits:
     memory: 8Gi
  requests:
    cpu: 1
    memory: 2Gi

hpa:
  enabled: false

metrics:
  enabled: false

rbac:
  enabled: true
  serviceaccount:
    create: true
    name: nextcloud-serviceaccount

redis:
  enabled: false

nodeSelector:
  clt.milco.casa/node-performance: high

tolerations:
  - key: "nvidia.com/gpu"
    operator: "Equal"
    effect: "NoSchedule"

# # Post-installation job to configure Keycloak OIDC
# extraInitContainers:
#   - name: configure-oidc
#     image: nextcloud:fpm
#     command:
#       - sh
#       - -c
#       - |
#         # Wait for Nextcloud to be ready
#         echo "Waiting for Nextcloud to be available..."
#         while ! php /var/www/html/occ status --no-warnings; do
#           echo "Still waiting for Nextcloud..."
#           sleep 15
#         done

#         echo "Nextcloud is ready, installing OIDC app..."

#         # Install and enable OIDC app
#         php /var/www/html/occ app:install user_oidc || echo "OIDC app already installed"
#         php /var/www/html/occ app:enable user_oidc || echo "OIDC app already enabled"

#         # Configure Keycloak OIDC provider
#         echo "Configuring Keycloak OIDC provider..."
#         php /var/www/html/occ user_oidc:provider add \
#           --provider-name="Keycloak" \
#           --client-id="$KEYCLOAK_CLIENT_ID" \
#           --client-secret="$KEYCLOAK_CLIENT_SECRET" \
#           --discovery-uri="https://sso.clt.milco.casa/realms/YOUR_REALM/.well-known/openid_configuration" \
#           --unique-uid=1 \
#           --check-bearer=0 || echo "Provider may already exist"

#         echo "OIDC configuration completed"
#     env:
#       # Keycloak credentials from secrets
#       - name: KEYCLOAK_CLIENT_ID
#         valueFrom:
#           secretKeyRef:
#             name: nextcloud-secrets
#             key: client-id
#       - name: KEYCLOAK_CLIENT_SECRET
#         valueFrom:
#           secretKeyRef:
#             name: nextcloud-secrets
#             key: client-secret
#       - name: POSTGRES_PASSWORD
#         valueFrom:
#           secretKeyRef:
#             name: nextcloud-secrets
#             key: db_user_password
#     volumeMounts:
#       - name: nextcloud-data
#         mountPath: /var/www/html
#         subPath: root
#       - name: nextcloud-data
#         mountPath: /var/www/html/data
#         subPath: data
#       - name: nextcloud-data
#         mountPath: /var/www/html/config
#         subPath: config
#       - name: nextcloud-data
#         mountPath: /var/www/html/custom_apps
#         subPath: custom_apps
#       - name: nextcloud-data
#         mountPath: /var/www/html/themes
#         subPath: themes
