image:
  repository: nextcloud
  flavor: fpm
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: "traefik"
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6
  tls:
    - secretName: wildcard.clt.milco.casa
      hosts:
        - nextcloud.clt.milco.casa

phpClientHttpsFix:
  enabled: false
  protocol: https

nextcloud:
  host: nextcloud.clt.milco.casa
  existingSecret:
    enabled: true
    secretName: nextcloud-secrets
    usernameKey: admin_user
    passwordKey: admin_password
  containerPort: 8080
  datadir: /var/www/html/data
  trustedDomains:
    - nextcloud.clt.milco.casa
    - nextcloud.nextcloud.svc.cluster.local
    - nextcloud.nextcloud.svc
  ## SMTP configuration
  mail:
    enabled: false
  ## Primary ObjectStore options
  objectStore:
    s3:
      enabled: false

nginx:
  enabled: true
  image:
    repository: nginx
    tag: alpine
    pullPolicy: IfNotPresent
  containerPort: 8080
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6

internalDatabase:
  enabled: false
externalDatabase:
  enabled: true
  type: postgresql
  host: "nextcloud-postgresql-0"
  existingSecret:
    enabled: true
    secretName: nextcloud-secrets
    usernameKey: db_username
    passwordKey: db_password

postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        username: nextcloud
        existingSecret: "nextcloud-secrets"
        secretKeys:
          adminPasswordKey: "db_password"
          userPasswordKey: "db_password"
          replicationPasswordKey: "db_replication_password"
  primary:
    persistence:
      enabled: true

collabora:
  enabled: false
cronjob:
  enabled: true

service:
  type: ClusterIP
  port: 8080
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6

persistence:
  enabled: true
  storageClass: "cephfs"
  accessMode: ReadWriteMany
  size: 500Gi

hpa:
  enabled: false

metrics:
  enabled: false

rbac:
  enabled: true
  serviceaccount:
    create: true
    name: nextcloud-serviceaccount
