image:
  repository: nextcloud
  flavor: fpm
  pullPolicy: IfNotPresent

ingress:
  enabled: true
  className: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: nextcloud-nextcloud-redirectregex@kubernetescrd,nextcloud-nextcloud-headers@kubernetescrd
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6
  hosts:
    - host: nextcloud.clt.milco.casa
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - nextcloud.clt.milco.casa

phpClientHttpsFix:
  enabled: false
  protocol: https

nextcloud:
  host: nextcloud.clt.milco.casa
  extraEnv:
    - name: TRUSTED_PROXIES
      value: "10.200.0.0/16 172.16.0.0/12"
    - name: OVERWRITECLIURL
      value: "https://nextcloud.clt.milco.casa"
    - name: OVERWRITEPROTOCOL
      value: "https"
    - name: OVERWRITEHOST
      value: "nextcloud.clt.milco.casa"
    - name: NEXTCLOUD_TRUSTED_DOMAINS
      value: "nextcloud.clt.milco.casa"
    - name: NEXTCLOUD_CONFIG_KEYCLOAK_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: nextcloud-secrets
          key: client-secret

  existingSecret:
    enabled: true
    secretName: nextcloud-secrets
    usernameKey: admin_user
    passwordKey: admin_password
  containerPort: 8080
  datadir: /var/www/html/data
  trustedDomains:
    - nextcloud.clt.milco.casa
    - nextcloud.nextcloud.svc.cluster.local
    - nextcloud.nextcloud.svc
  ## SMTP configuration
  mail:
    enabled: false
  ## Primary ObjectStore options
  objectStore:
    s3:
      enabled: false

  configs:
    config.php: |
      <?php
      $CONFIG = array (
        'allow_user_to_change_display_name' => false,
        'lost_password_link' => 'disabled',
        'oidc_login_provider_url' => 'https://sso.clt.milco.casa/realms/homelab',
        'oidc_login_client_id' => 'nextcloud',
        'oidc_login_client_secret' => '{{ .Values.keycloakClientSecret }}',
        'oidc_login_auto_redirect' => false,
        'oidc_login_logout_url' => 'https://sso.clt.milco.casa/realms/homelab/protocol/openid-connect/logout?redirect_uri=https://nextcloud.clt.milco.casa/',
        'oidc_login_default_quota' => '1000000000',
        'oidc_login_button_text' => 'Login with Homelab',
        'oidc_login_attributes' => array (
          'id' => 'preferred_username',
          'name' => 'name',
          'mail' => 'email',
          'groups' => 'ownCloudGroups',
        ),
        'oidc_login_scope' => 'openid profile email',
        'overwriteprotocol' => 'https',
        'overwrite.cli.url' => 'https://nextcloud.clt.milco.casa',
      );

# Reference the Kubernetes Secret for the client secret
keycloakClientSecret: "{{ .Values.nextcloud.configs.keycloakClientSecret }}"

nginx:
  enabled: true
  image:
    repository: nginx
    tag: alpine
    pullPolicy: IfNotPresent
  containerPort: 8080
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6

internalDatabase:
  enabled: false
externalDatabase:
  enabled: true
  type: postgresql
  host: "nextcloud-postgresql-0"
  existingSecret:
    enabled: true
    secretName: nextcloud-secrets
    usernameKey: db_username
    passwordKey: db_password

postgresql:
  enabled: true
  global:
    postgresql:
      auth:
        username: nextcloud
        existingSecret: "nextcloud-secrets"
        secretKeys:
          adminPasswordKey: "db_password"
          userPasswordKey: "db_password"
          replicationPasswordKey: "db_replication_password"
  primary:
    persistence:
      enabled: true

collabora:
  enabled: false
cronjob:
  enabled: true

service:
  type: ClusterIP
  port: 8080
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6

persistence:
  enabled: true
  storageClass: "cephfs"
  accessMode: ReadWriteMany
  size: 8Gi
  nextcloudData:
    enabled: true
    existingClaim: nextcloud-data

resources:
  requests:
    cpu: "6"
    memory: "12Gi"

hpa:
  enabled: false

metrics:
  enabled: false

rbac:
  enabled: true
  serviceaccount:
    create: true
    name: nextcloud-serviceaccount

nodeSelector:
  clt.milco.casa/node-performance: high

tolerations:
  - key: "nvidia.com/gpu"
    operator: "Equal"
    effect: "NoSchedule"
