---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-admin-users
subjects:
  - kind: ServiceAccount
    name: admin-bmilco
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-bmilco
  namespace: kube-system
secrets:
  - name: admin-bmilco
---
apiVersion: v1
kind: Secret
metadata:
  name: admin-bmilco
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: admin-bmilco
type: kubernetes.io/service-account-token
