---

- name: Create helm repo for cert-manager
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

- name: Deploy cert-manager
  kubernetes.core.helm:
    name: cert-manager
    chart_version: "{{ cert_manager_version }}"
    chart_ref: jetstack/cert-manager
    release_namespace: "{{ cert_manager_namespace }}"
    create_namespace: true
    update_repo_cache: true
    values: "{{ lookup('template', 'cert-manager-values.yaml.j2') | from_yaml }}"

- name: Deploy solvers
  kubernetes.core.k8s:
    state: present
    template: solvers.yaml.j2

- name: Deploy {{ lan_tld }} cert
  kubernetes.core.k8s:
    state: present
    namespace: "{{ cert_manager_namespace }}"
    template: "{{ item }}"
  loop:
    - wildcard.milco.casa.yaml.j2
...
