---

- name: Create helm repo for cert-manager
  kubernetes.core.helm_repository:
    name: jetstack
    repo_url: https://charts.jetstack.io

- name: Deploy cert-manager
  kubernetes.core.helm:
    name: cert-manager
    chart_version: "{{ cert_manager_version }}"
    chart_ref: jetstack/cert-manager
    release_namespace: "{{ cert_manager_namespace }}"
    create_namespace: true
    update_repo_cache: true
    values: "{{ lookup('template', 'cert-manager-values.yaml.j2') | from_yaml }}"

- name: Deploy solvers
  kubernetes.core.k8s:
    state: present
    template: solvers.yaml.j2

- name: Git Porkbun webhook
  ansible.builtin.git:
    repo: 'https://github.com/mdonoughe/porkbun-webhook.git'
    dest: "{{ ansible_env.PWD }}/porkbun-webhook"
    version: v0.1.5

- name: Deploy porkbun webhook
  kubernetes.core.helm:
    name: porkbun-webhook
    chart_ref: "{{ ansible_env.PWD }}/porkbun-webhook/deploy/porkbun-webhook"
    release_namespace: "{{ cert_manager_namespace }}"
    values: "{{ lookup('template', 'porkbun-values.yaml.j2') | from_yaml }}"

- name: Deploy porkbun rbac
  kubernetes.core.k8s:
    namespace: "{{ cert_manager_namespace }}"
    src: "{{ ansible_env.PWD }}/porkbun-webhook/rbac.yaml"
    state: present

- name: Deploy acme api keys
  kubernetes.core.k8s:
    state: present
    template: porkbun-key.yaml.j2

- name: Deploy {{ lan_tld }} cert
  kubernetes.core.k8s:
    state: present
    namespace: "{{ cert_manager_namespace }}"
    template: wildcard.milco.casa.yaml.j2
...
