---

- name: Install desired packages
  ansible.builtin.opkg:
    name: acme-acmesh,acme-acmesh-dnsapi,luci-app-acme
    state: present
    update_cache: yes

- name: Configure acme
  ansible.builtin.template:
    src: acme.j2
    dest: /etc/config/acme
    owner: root
    group: root
    mode: '0600'
  notify: restart acme
